// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_stats.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChannels = `-- name: CountChannels :one
SELECT count(*) FROM channels WHERE is_archived = FALSE
`

func (q *Queries) CountChannels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countChannels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFiles = `-- name: CountFiles :one
SELECT count(*) FROM files
`

func (q *Queries) CountFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMessages = `-- name: CountMessages :one
SELECT count(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users WHERE is_deactivated = FALSE
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_deactivated = TRUE WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const listAllChannelsWithStats = `-- name: ListAllChannelsWithStats :many
SELECT
    c.id,
    c.name,
    c.slug,
    c.type,
    c.is_archived,
    c.created_at,
    (SELECT count(*) FROM channel_members cm WHERE cm.channel_id = c.id) AS member_count,
    (SELECT count(*) FROM messages m WHERE m.channel_id = c.id) AS message_count
FROM channels c
ORDER BY c.name
`

type ListAllChannelsWithStatsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Type         string             `json:"type"`
	IsArchived   bool               `json:"is_archived"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	MemberCount  int64              `json:"member_count"`
	MessageCount int64              `json:"message_count"`
}

func (q *Queries) ListAllChannelsWithStats(ctx context.Context) ([]ListAllChannelsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listAllChannelsWithStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllChannelsWithStatsRow{}
	for rows.Next() {
		var i ListAllChannelsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.IsArchived,
			&i.CreatedAt,
			&i.MemberCount,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsersAdmin = `-- name: SearchUsersAdmin :many
SELECT id, username, email, display_name, avatar_url, role, status, last_seen, is_bot, is_deactivated, created_at
FROM users
WHERE
    ($1::text = '' OR username ILIKE '%' || $1 || '%' OR display_name ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%')
ORDER BY display_name
LIMIT $2 OFFSET $3
`

type SearchUsersAdminParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchUsersAdminRow struct {
	ID            pgtype.UUID        `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	Role          string             `json:"role"`
	Status        string             `json:"status"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
	IsBot         bool               `json:"is_bot"`
	IsDeactivated bool               `json:"is_deactivated"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchUsersAdmin(ctx context.Context, arg SearchUsersAdminParams) ([]SearchUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, searchUsersAdmin, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersAdminRow{}
	for rows.Next() {
		var i SearchUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.LastSeen,
			&i.IsBot,
			&i.IsDeactivated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalStorageBytes = `-- name: TotalStorageBytes :one
SELECT coalesce(sum(size_bytes), 0)::bigint FROM files
`

func (q *Queries) TotalStorageBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, totalStorageBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
