// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (user_id, slug, name, emoji, description, scope, status, gateway_url, gateway_token, model, system_prompt, max_tokens, temperature, max_context_messages)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) RETURNING id, user_id, slug, name, emoji, avatar_url, description, scope, status, gateway_url, gateway_token, model, system_prompt, max_tokens, temperature, bridge_url, use_bridge, max_context_messages, auto_join_channels, capabilities, created_at, updated_at
`

type CreateAgentParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	Slug               string      `json:"slug"`
	Name               string      `json:"name"`
	Emoji              pgtype.Text `json:"emoji"`
	Description        pgtype.Text `json:"description"`
	Scope              pgtype.Text `json:"scope"`
	Status             string      `json:"status"`
	GatewayUrl         string      `json:"gateway_url"`
	GatewayToken       pgtype.Text `json:"gateway_token"`
	Model              string      `json:"model"`
	SystemPrompt       pgtype.Text `json:"system_prompt"`
	MaxTokens          int32       `json:"max_tokens"`
	Temperature        float32     `json:"temperature"`
	MaxContextMessages int32       `json:"max_context_messages"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.UserID,
		arg.Slug,
		arg.Name,
		arg.Emoji,
		arg.Description,
		arg.Scope,
		arg.Status,
		arg.GatewayUrl,
		arg.GatewayToken,
		arg.Model,
		arg.SystemPrompt,
		arg.MaxTokens,
		arg.Temperature,
		arg.MaxContextMessages,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Emoji,
		&i.AvatarUrl,
		&i.Description,
		&i.Scope,
		&i.Status,
		&i.GatewayUrl,
		&i.GatewayToken,
		&i.Model,
		&i.SystemPrompt,
		&i.MaxTokens,
		&i.Temperature,
		&i.BridgeUrl,
		&i.UseBridge,
		&i.MaxContextMessages,
		&i.AutoJoinChannels,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentSession = `-- name: CreateAgentSession :one
INSERT INTO agent_sessions (agent_id, user_id, title) VALUES ($1, $2, $3) RETURNING id, agent_id, user_id, title, is_active, created_at, updated_at
`

type CreateAgentSessionParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Title   pgtype.Text `json:"title"`
}

func (q *Queries) CreateAgentSession(ctx context.Context, arg CreateAgentSessionParams) (AgentSession, error) {
	row := q.db.QueryRow(ctx, createAgentSession, arg.AgentID, arg.UserID, arg.Title)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.Title,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentUsage = `-- name: CreateAgentUsage :exec
INSERT INTO agent_usage (agent_id, user_id, channel_id, session_id, message_id, input_tokens, output_tokens, cost_usd, response_time_ms, model_used, source)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAgentUsageParams struct {
	AgentID        pgtype.UUID    `json:"agent_id"`
	UserID         pgtype.UUID    `json:"user_id"`
	ChannelID      pgtype.UUID    `json:"channel_id"`
	SessionID      pgtype.UUID    `json:"session_id"`
	MessageID      pgtype.UUID    `json:"message_id"`
	InputTokens    int32          `json:"input_tokens"`
	OutputTokens   int32          `json:"output_tokens"`
	CostUsd        pgtype.Numeric `json:"cost_usd"`
	ResponseTimeMs int32          `json:"response_time_ms"`
	ModelUsed      pgtype.Text    `json:"model_used"`
	Source         pgtype.Text    `json:"source"`
}

func (q *Queries) CreateAgentUsage(ctx context.Context, arg CreateAgentUsageParams) error {
	_, err := q.db.Exec(ctx, createAgentUsage,
		arg.AgentID,
		arg.UserID,
		arg.ChannelID,
		arg.SessionID,
		arg.MessageID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostUsd,
		arg.ResponseTimeMs,
		arg.ModelUsed,
		arg.Source,
	)
	return err
}

const getAgentBySlug = `-- name: GetAgentBySlug :one
SELECT id, user_id, slug, name, emoji, avatar_url, description, scope, status, gateway_url, gateway_token, model, system_prompt, max_tokens, temperature, bridge_url, use_bridge, max_context_messages, auto_join_channels, capabilities, created_at, updated_at FROM agents WHERE slug = $1
`

func (q *Queries) GetAgentBySlug(ctx context.Context, slug string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentBySlug, slug)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Emoji,
		&i.AvatarUrl,
		&i.Description,
		&i.Scope,
		&i.Status,
		&i.GatewayUrl,
		&i.GatewayToken,
		&i.Model,
		&i.SystemPrompt,
		&i.MaxTokens,
		&i.Temperature,
		&i.BridgeUrl,
		&i.UseBridge,
		&i.MaxContextMessages,
		&i.AutoJoinChannels,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByUserID = `-- name: GetAgentByUserID :one
SELECT id, user_id, slug, name, emoji, avatar_url, description, scope, status, gateway_url, gateway_token, model, system_prompt, max_tokens, temperature, bridge_url, use_bridge, max_context_messages, auto_join_channels, capabilities, created_at, updated_at FROM agents WHERE user_id = $1
`

func (q *Queries) GetAgentByUserID(ctx context.Context, userID pgtype.UUID) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByUserID, userID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Slug,
		&i.Name,
		&i.Emoji,
		&i.AvatarUrl,
		&i.Description,
		&i.Scope,
		&i.Status,
		&i.GatewayUrl,
		&i.GatewayToken,
		&i.Model,
		&i.SystemPrompt,
		&i.MaxTokens,
		&i.Temperature,
		&i.BridgeUrl,
		&i.UseBridge,
		&i.MaxContextMessages,
		&i.AutoJoinChannels,
		&i.Capabilities,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentSession = `-- name: GetAgentSession :one
SELECT id, agent_id, user_id, title, is_active, created_at, updated_at FROM agent_sessions WHERE id = $1
`

func (q *Queries) GetAgentSession(ctx context.Context, id pgtype.UUID) (AgentSession, error) {
	row := q.db.QueryRow(ctx, getAgentSession, id)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.Title,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, u.username, u.display_name, u.avatar_url, u.is_bot
FROM messages m JOIN users u ON u.id = m.user_id
WHERE m.channel_id = $1
ORDER BY m.created_at ASC
`

type GetSessionMessagesRow struct {
	ID           pgtype.UUID        `json:"id"`
	ChannelID    pgtype.UUID        `json:"channel_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ThreadID     pgtype.UUID        `json:"thread_id"`
	Content      string             `json:"content"`
	ContentType  string             `json:"content_type"`
	EditedAt     pgtype.Timestamptz `json:"edited_at"`
	IsPinned     bool               `json:"is_pinned"`
	Metadata     json.RawMessage    `json:"metadata"`
	SearchVector interface{}        `json:"search_vector"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	IsBot        bool               `json:"is_bot"`
}

func (q *Queries) GetSessionMessages(ctx context.Context, channelID pgtype.UUID) ([]GetSessionMessagesRow, error) {
	rows, err := q.db.Query(ctx, getSessionMessages, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionMessagesRow{}
	for rows.Next() {
		var i GetSessionMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ThreadID,
			&i.Content,
			&i.ContentType,
			&i.EditedAt,
			&i.IsPinned,
			&i.Metadata,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessions = `-- name: ListAgentSessions :many
SELECT id, agent_id, user_id, title, is_active, created_at, updated_at FROM agent_sessions WHERE agent_id = $1 AND user_id = $2 ORDER BY updated_at DESC
`

type ListAgentSessionsParams struct {
	AgentID pgtype.UUID `json:"agent_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListAgentSessions(ctx context.Context, arg ListAgentSessionsParams) ([]AgentSession, error) {
	rows, err := q.db.Query(ctx, listAgentSessions, arg.AgentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentSession{}
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.UserID,
			&i.Title,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, user_id, slug, name, emoji, avatar_url, description, scope, status, gateway_url, gateway_token, model, system_prompt, max_tokens, temperature, bridge_url, use_bridge, max_context_messages, auto_join_channels, capabilities, created_at, updated_at FROM agents WHERE status = 'active' ORDER BY name
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Slug,
			&i.Name,
			&i.Emoji,
			&i.AvatarUrl,
			&i.Description,
			&i.Scope,
			&i.Status,
			&i.GatewayUrl,
			&i.GatewayToken,
			&i.Model,
			&i.SystemPrompt,
			&i.MaxTokens,
			&i.Temperature,
			&i.BridgeUrl,
			&i.UseBridge,
			&i.MaxContextMessages,
			&i.AutoJoinChannels,
			&i.Capabilities,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentSessionTitle = `-- name: UpdateAgentSessionTitle :exec
UPDATE agent_sessions SET title = $2 WHERE id = $1
`

type UpdateAgentSessionTitleParams struct {
	ID    pgtype.UUID `json:"id"`
	Title pgtype.Text `json:"title"`
}

func (q *Queries) UpdateAgentSessionTitle(ctx context.Context, arg UpdateAgentSessionTitleParams) error {
	_, err := q.db.Exec(ctx, updateAgentSessionTitle, arg.ID, arg.Title)
	return err
}
