// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, token_prefix, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, is_revoked, created_at
`

type CreateAPITokenParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
`

type DeleteAPITokenParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.UserID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT t.id, t.user_id, t.name, t.token_hash, t.token_prefix, t.scopes, t.expires_at, t.last_used_at, t.is_revoked, t.created_at, u.username, u.role AS user_role
FROM api_tokens t
JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1 AND t.is_revoked = FALSE
`

type GetAPITokenByHashRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	IsRevoked   bool               `json:"is_revoked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	UserRole    string             `json:"user_role"`
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
		&i.Username,
		&i.UserRole,
	)
	return i, err
}

const listAPITokensByUser = `-- name: ListAPITokensByUser :many
SELECT id, user_id, name, token_hash, token_prefix, scopes, expires_at, last_used_at, is_revoked, created_at FROM api_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPITokensByUser(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.IsRevoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE api_tokens SET is_revoked = TRUE WHERE id = $1 AND user_id = $2
`

type RevokeAPITokenParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID)
	return err
}

const updateTokenLastUsed = `-- name: UpdateTokenLastUsed :exec
UPDATE api_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateTokenLastUsed, id)
	return err
}
