// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_config.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAppConfig = `-- name: GetAppConfig :one
SELECT key, value, updated_at, updated_by FROM app_config WHERE key = $1
`

func (q *Queries) GetAppConfig(ctx context.Context, key string) (AppConfig, error) {
	row := q.db.QueryRow(ctx, getAppConfig, key)
	var i AppConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listAppConfig = `-- name: ListAppConfig :many
SELECT key, value, updated_at, updated_by FROM app_config ORDER BY key
`

func (q *Queries) ListAppConfig(ctx context.Context) ([]AppConfig, error) {
	rows, err := q.db.Query(ctx, listAppConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppConfig{}
	for rows.Next() {
		var i AppConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAppConfig = `-- name: UpsertAppConfig :one
INSERT INTO app_config (key, value, updated_at, updated_by)
VALUES ($1, $2, NOW(), $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = NOW(),
    updated_by = EXCLUDED.updated_by
RETURNING key, value, updated_at, updated_by
`

type UpsertAppConfigParams struct {
	Key       string      `json:"key"`
	Value     []byte      `json:"value"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertAppConfig(ctx context.Context, arg UpsertAppConfigParams) (AppConfig, error) {
	row := q.db.QueryRow(ctx, upsertAppConfig, arg.Key, arg.Value, arg.UpdatedBy)
	var i AppConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
