// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel_members.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelMember = `-- name: AddChannelMember :exec
INSERT INTO channel_members (channel_id, user_id, role)
VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Role      string      `json:"role"`
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error {
	_, err := q.db.Exec(ctx, addChannelMember, arg.ChannelID, arg.UserID, arg.Role)
	return err
}

const getChannelMember = `-- name: GetChannelMember :one
SELECT channel_id, user_id, role, joined_at, last_read_msg_id, muted, notifications, hidden FROM channel_members WHERE channel_id = $1 AND user_id = $2
`

type GetChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetChannelMember(ctx context.Context, arg GetChannelMemberParams) (ChannelMember, error) {
	row := q.db.QueryRow(ctx, getChannelMember, arg.ChannelID, arg.UserID)
	var i ChannelMember
	err := row.Scan(
		&i.ChannelID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.LastReadMsgID,
		&i.Muted,
		&i.Notifications,
		&i.Hidden,
	)
	return i, err
}

const getChannelMembers = `-- name: GetChannelMembers :many
SELECT u.id, u.username, u.display_name, u.avatar_url, u.status, u.is_bot, cm.role, cm.joined_at
FROM channel_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.channel_id = $1
ORDER BY u.display_name
`

type GetChannelMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Status      string             `json:"status"`
	IsBot       bool               `json:"is_bot"`
	Role        string             `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetChannelMembers(ctx context.Context, channelID pgtype.UUID) ([]GetChannelMembersRow, error) {
	rows, err := q.db.Query(ctx, getChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetChannelMembersRow{}
	for rows.Next() {
		var i GetChannelMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Status,
			&i.IsBot,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM messages m
JOIN channel_members cm ON cm.channel_id = m.channel_id AND cm.user_id = $2
WHERE m.channel_id = $1
  AND (cm.last_read_msg_id IS NULL OR m.created_at > (SELECT created_at FROM messages WHERE id = cm.last_read_msg_id))
`

type GetUnreadCountParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetUnreadCount(ctx context.Context, arg GetUnreadCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, arg.ChannelID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isChannelMember = `-- name: IsChannelMember :one
SELECT EXISTS(SELECT 1 FROM channel_members WHERE channel_id = $1 AND user_id = $2)
`

type IsChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsChannelMember(ctx context.Context, arg IsChannelMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMember, arg.ChannelID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeChannelMember = `-- name: RemoveChannelMember :exec
DELETE FROM channel_members WHERE channel_id = $1 AND user_id = $2
`

type RemoveChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error {
	_, err := q.db.Exec(ctx, removeChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const setChannelHidden = `-- name: SetChannelHidden :exec
UPDATE channel_members SET hidden = $3, muted = $3 WHERE channel_id = $1 AND user_id = $2
`

type SetChannelHiddenParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Hidden    bool        `json:"hidden"`
}

func (q *Queries) SetChannelHidden(ctx context.Context, arg SetChannelHiddenParams) error {
	_, err := q.db.Exec(ctx, setChannelHidden, arg.ChannelID, arg.UserID, arg.Hidden)
	return err
}

const unhideChannel = `-- name: UnhideChannel :exec
UPDATE channel_members SET hidden = FALSE WHERE channel_id = $1 AND user_id = $2
`

type UnhideChannelParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UnhideChannel(ctx context.Context, arg UnhideChannelParams) error {
	_, err := q.db.Exec(ctx, unhideChannel, arg.ChannelID, arg.UserID)
	return err
}

const updateLastRead = `-- name: UpdateLastRead :exec
UPDATE channel_members SET last_read_msg_id = $3 WHERE channel_id = $1 AND user_id = $2
`

type UpdateLastReadParams struct {
	ChannelID     pgtype.UUID `json:"channel_id"`
	UserID        pgtype.UUID `json:"user_id"`
	LastReadMsgID pgtype.UUID `json:"last_read_msg_id"`
}

func (q *Queries) UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error {
	_, err := q.db.Exec(ctx, updateLastRead, arg.ChannelID, arg.UserID, arg.LastReadMsgID)
	return err
}
