// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, slug, description, type, topic, created_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at
`

type CreateChannelParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	Topic       pgtype.Text `json:"topic"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Type,
		arg.Topic,
		arg.CreatedBy,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelBySlug = `-- name: GetChannelBySlug :one
SELECT id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at FROM channels WHERE slug = $1
`

func (q *Queries) GetChannelBySlug(ctx context.Context, slug string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelBySlug, slug)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDMChannel = `-- name: GetDMChannel :one
SELECT c.id, c.name, c.slug, c.description, c.type, c.topic, c.created_by, c.is_archived, c.created_at, c.updated_at FROM channels c
JOIN channel_members cm1 ON cm1.channel_id = c.id AND cm1.user_id = $1
JOIN channel_members cm2 ON cm2.channel_id = c.id AND cm2.user_id = $2
WHERE c.type = 'dm'
`

type GetDMChannelParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

func (q *Queries) GetDMChannel(ctx context.Context, arg GetDMChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getDMChannel, arg.UserID, arg.UserID_2)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannelsForUser = `-- name: ListChannelsForUser :many
SELECT c.id, c.name, c.slug, c.description, c.type, c.topic, c.created_by, c.is_archived, c.created_at, c.updated_at FROM channels c
JOIN channel_members cm ON cm.channel_id = c.id
WHERE cm.user_id = $1 AND c.is_archived = FALSE
ORDER BY c.name
`

func (q *Queries) ListChannelsForUser(ctx context.Context, userID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Topic,
			&i.CreatedBy,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicChannels = `-- name: ListPublicChannels :many
SELECT id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at FROM channels WHERE type = 'public' AND is_archived = FALSE ORDER BY name
`

func (q *Queries) ListPublicChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listPublicChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Topic,
			&i.CreatedBy,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels SET
    name = coalesce($2, name),
    description = coalesce($3, description),
    topic = coalesce($4, topic),
    is_archived = coalesce($5, is_archived)
WHERE id = $1 RETURNING id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at
`

type UpdateChannelParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Topic       pgtype.Text `json:"topic"`
	IsArchived  pgtype.Bool `json:"is_archived"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Topic,
		arg.IsArchived,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
