// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, slug, description, type, topic, created_by, read_only)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at, read_only, retention_days, last_message_at
`

type CreateChannelParams struct {
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	Topic       pgtype.Text `json:"topic"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	ReadOnly    bool        `json:"read_only"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Type,
		arg.Topic,
		arg.CreatedBy,
		arg.ReadOnly,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.RetentionDays,
		&i.LastMessageAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at, read_only, retention_days, last_message_at FROM channels WHERE id = $1
`

func (q *Queries) GetChannelByID(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.RetentionDays,
		&i.LastMessageAt,
	)
	return i, err
}

const getChannelBySlug = `-- name: GetChannelBySlug :one
SELECT id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at, read_only, retention_days, last_message_at FROM channels WHERE slug = $1
`

func (q *Queries) GetChannelBySlug(ctx context.Context, slug string) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelBySlug, slug)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.RetentionDays,
		&i.LastMessageAt,
	)
	return i, err
}

const getChannelReadOnly = `-- name: GetChannelReadOnly :one
SELECT read_only FROM channels WHERE id = $1
`

func (q *Queries) GetChannelReadOnly(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getChannelReadOnly, id)
	var read_only bool
	err := row.Scan(&read_only)
	return read_only, err
}

const getDMChannel = `-- name: GetDMChannel :one
SELECT c.id, c.name, c.slug, c.description, c.type, c.topic, c.created_by, c.is_archived, c.created_at, c.updated_at, c.read_only, c.retention_days, c.last_message_at FROM channels c
JOIN channel_members cm1 ON cm1.channel_id = c.id AND cm1.user_id = $1
JOIN channel_members cm2 ON cm2.channel_id = c.id AND cm2.user_id = $2
WHERE c.type = 'dm'
`

type GetDMChannelParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

func (q *Queries) GetDMChannel(ctx context.Context, arg GetDMChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, getDMChannel, arg.UserID, arg.UserID_2)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.RetentionDays,
		&i.LastMessageAt,
	)
	return i, err
}

const getDMDisplayNames = `-- name: GetDMDisplayNames :many
SELECT
    cm.channel_id,
    COALESCE(
        (SELECT u.display_name FROM channel_members cm2
         JOIN users u ON u.id = cm2.user_id
         WHERE cm2.channel_id = cm.channel_id AND cm2.user_id <> $1
         LIMIT 1),
        c.name
    ) AS display_name
FROM channel_members cm
JOIN channels c ON c.id = cm.channel_id
WHERE cm.user_id = $1 AND c.type = 'dm'
`

type GetDMDisplayNamesRow struct {
	ChannelID   pgtype.UUID `json:"channel_id"`
	DisplayName string      `json:"display_name"`
}

// For each DM channel the user belongs to, return the other participant's display name.
// If no other member exists, falls back to the channel name.
func (q *Queries) GetDMDisplayNames(ctx context.Context, userID pgtype.UUID) ([]GetDMDisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, getDMDisplayNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDMDisplayNamesRow{}
	for rows.Next() {
		var i GetDMDisplayNamesRow
		if err := rows.Scan(&i.ChannelID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForUser = `-- name: ListChannelsForUser :many
SELECT c.id, c.name, c.slug, c.description, c.type, c.topic, c.created_by, c.is_archived, c.created_at, c.updated_at, c.read_only, c.retention_days, c.last_message_at FROM channels c
JOIN channel_members cm ON cm.channel_id = c.id
WHERE cm.user_id = $1 AND c.is_archived = FALSE AND cm.hidden = FALSE
  AND (
    $2::int = 0
    OR c.last_message_at >= NOW() - INTERVAL '1 day' * $2::int
    OR c.last_message_at IS NULL
  )
  -- Exclude orphan DMs (where the other participant is missing)
  AND (
    c.type <> 'dm'
    OR EXISTS (
      SELECT 1 FROM channel_members cm2
      WHERE cm2.channel_id = c.id AND cm2.user_id <> $1
    )
  )
ORDER BY c.name
`

type ListChannelsForUserParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 int32       `json:"column_2"`
}

func (q *Queries) ListChannelsForUser(ctx context.Context, arg ListChannelsForUserParams) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsForUser, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Topic,
			&i.CreatedBy,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadOnly,
			&i.RetentionDays,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHiddenChannelsForUser = `-- name: ListHiddenChannelsForUser :many
SELECT c.id, c.name, c.slug, c.description, c.type, c.topic, c.created_by, c.is_archived, c.created_at, c.updated_at, c.read_only, c.retention_days, c.last_message_at FROM channels c
JOIN channel_members cm ON cm.channel_id = c.id
WHERE cm.user_id = $1 AND cm.hidden = TRUE AND c.is_archived = FALSE
ORDER BY c.name
`

func (q *Queries) ListHiddenChannelsForUser(ctx context.Context, userID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listHiddenChannelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Topic,
			&i.CreatedBy,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadOnly,
			&i.RetentionDays,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicChannels = `-- name: ListPublicChannels :many
SELECT id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at, read_only, retention_days, last_message_at FROM channels WHERE type = 'public' AND is_archived = FALSE ORDER BY name
`

func (q *Queries) ListPublicChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listPublicChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Topic,
			&i.CreatedBy,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadOnly,
			&i.RetentionDays,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels SET
    name = coalesce($2, name),
    description = coalesce($3, description),
    topic = coalesce($4, topic),
    is_archived = coalesce($5, is_archived),
    read_only = coalesce($6, read_only),
    retention_days = coalesce($7, retention_days)
WHERE id = $1 RETURNING id, name, slug, description, type, topic, created_by, is_archived, created_at, updated_at, read_only, retention_days, last_message_at
`

type UpdateChannelParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          pgtype.Text `json:"name"`
	Description   pgtype.Text `json:"description"`
	Topic         pgtype.Text `json:"topic"`
	IsArchived    pgtype.Bool `json:"is_archived"`
	ReadOnly      pgtype.Bool `json:"read_only"`
	RetentionDays pgtype.Int4 `json:"retention_days"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Topic,
		arg.IsArchived,
		arg.ReadOnly,
		arg.RetentionDays,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Topic,
		&i.CreatedBy,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadOnly,
		&i.RetentionDays,
		&i.LastMessageAt,
	)
	return i, err
}

const updateChannelLastMessageAt = `-- name: UpdateChannelLastMessageAt :exec
UPDATE channels SET last_message_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateChannelLastMessageAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateChannelLastMessageAt, id)
	return err
}
