// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_emojis.sql

package repository

import (
	"context"
)

const createCustomEmoji = `-- name: CreateCustomEmoji :one
INSERT INTO custom_emojis (name, aliases, mime_type, storage_path)
VALUES ($1, $2, $3, $4) RETURNING id, name, aliases, mime_type, storage_path, created_at
`

type CreateCustomEmojiParams struct {
	Name        string   `json:"name"`
	Aliases     []string `json:"aliases"`
	MimeType    string   `json:"mime_type"`
	StoragePath string   `json:"storage_path"`
}

func (q *Queries) CreateCustomEmoji(ctx context.Context, arg CreateCustomEmojiParams) (CustomEmoji, error) {
	row := q.db.QueryRow(ctx, createCustomEmoji,
		arg.Name,
		arg.Aliases,
		arg.MimeType,
		arg.StoragePath,
	)
	var i CustomEmoji
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.MimeType,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomEmojiByName = `-- name: GetCustomEmojiByName :one
SELECT id, name, aliases, mime_type, storage_path, created_at FROM custom_emojis WHERE name = $1
`

func (q *Queries) GetCustomEmojiByName(ctx context.Context, name string) (CustomEmoji, error) {
	row := q.db.QueryRow(ctx, getCustomEmojiByName, name)
	var i CustomEmoji
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.MimeType,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomEmojis = `-- name: ListCustomEmojis :many
SELECT id, name, aliases, mime_type, storage_path, created_at FROM custom_emojis ORDER BY name
`

func (q *Queries) ListCustomEmojis(ctx context.Context) ([]CustomEmoji, error) {
	rows, err := q.db.Query(ctx, listCustomEmojis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomEmoji{}
	for rows.Next() {
		var i CustomEmoji
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Aliases,
			&i.MimeType,
			&i.StoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomEmoji = `-- name: UpsertCustomEmoji :one
INSERT INTO custom_emojis (name, aliases, mime_type, storage_path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name) DO UPDATE SET
    aliases = EXCLUDED.aliases,
    mime_type = EXCLUDED.mime_type,
    storage_path = EXCLUDED.storage_path
RETURNING id, name, aliases, mime_type, storage_path, created_at
`

type UpsertCustomEmojiParams struct {
	Name        string   `json:"name"`
	Aliases     []string `json:"aliases"`
	MimeType    string   `json:"mime_type"`
	StoragePath string   `json:"storage_path"`
}

func (q *Queries) UpsertCustomEmoji(ctx context.Context, arg UpsertCustomEmojiParams) (CustomEmoji, error) {
	row := q.db.QueryRow(ctx, upsertCustomEmoji,
		arg.Name,
		arg.Aliases,
		arg.MimeType,
		arg.StoragePath,
	)
	var i CustomEmoji
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Aliases,
		&i.MimeType,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}
