// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_tokens.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllDeviceTokensForUser = `-- name: DeleteAllDeviceTokensForUser :exec
DELETE FROM device_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAllDeviceTokensForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllDeviceTokensForUser, userID)
	return err
}

const getDeviceTokensForUser = `-- name: GetDeviceTokensForUser :many
SELECT id, user_id, token, platform, created_at, updated_at FROM device_tokens WHERE user_id = $1
`

func (q *Queries) GetDeviceTokensForUser(ctx context.Context, userID pgtype.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeviceTokensForUsers = `-- name: GetDeviceTokensForUsers :many
SELECT id, user_id, token, platform, created_at, updated_at FROM device_tokens WHERE user_id = ANY($1::uuid[])
`

func (q *Queries) GetDeviceTokensForUsers(ctx context.Context, dollar_1 []pgtype.UUID) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensForUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerDeviceToken = `-- name: RegisterDeviceToken :exec
INSERT INTO device_tokens (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, token) DO UPDATE SET updated_at = now()
`

type RegisterDeviceTokenParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Token    string      `json:"token"`
	Platform string      `json:"platform"`
}

func (q *Queries) RegisterDeviceToken(ctx context.Context, arg RegisterDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, registerDeviceToken, arg.UserID, arg.Token, arg.Platform)
	return err
}

const unregisterDeviceToken = `-- name: UnregisterDeviceToken :exec
DELETE FROM device_tokens WHERE user_id = $1 AND token = $2
`

type UnregisterDeviceTokenParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Token  string      `json:"token"`
}

func (q *Queries) UnregisterDeviceToken(ctx context.Context, arg UnregisterDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, unregisterDeviceToken, arg.UserID, arg.Token)
	return err
}
