// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFilesByBackend = `-- name: CountFilesByBackend :many
SELECT storage_backend, COUNT(*) AS count FROM files GROUP BY storage_backend
`

type CountFilesByBackendRow struct {
	StorageBackend string `json:"storage_backend"`
	Count          int64  `json:"count"`
}

func (q *Queries) CountFilesByBackend(ctx context.Context) ([]CountFilesByBackendRow, error) {
	rows, err := q.db.Query(ctx, countFilesByBackend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFilesByBackendRow{}
	for rows.Next() {
		var i CountFilesByBackendRow
		if err := rows.Scan(&i.StorageBackend, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (message_id, user_id, channel_id, filename, original_name, mime_type, size_bytes, storage_path, thumbnail_path, storage_backend)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, message_id, user_id, channel_id, filename, original_name, mime_type, size_bytes, storage_path, thumbnail_path, created_at, storage_backend
`

type CreateFileParams struct {
	MessageID      pgtype.UUID `json:"message_id"`
	UserID         pgtype.UUID `json:"user_id"`
	ChannelID      pgtype.UUID `json:"channel_id"`
	Filename       string      `json:"filename"`
	OriginalName   string      `json:"original_name"`
	MimeType       string      `json:"mime_type"`
	SizeBytes      int64       `json:"size_bytes"`
	StoragePath    string      `json:"storage_path"`
	ThumbnailPath  pgtype.Text `json:"thumbnail_path"`
	StorageBackend string      `json:"storage_backend"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.MessageID,
		arg.UserID,
		arg.ChannelID,
		arg.Filename,
		arg.OriginalName,
		arg.MimeType,
		arg.SizeBytes,
		arg.StoragePath,
		arg.ThumbnailPath,
		arg.StorageBackend,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.ChannelID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.CreatedAt,
		&i.StorageBackend,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, message_id, user_id, channel_id, filename, original_name, mime_type, size_bytes, storage_path, thumbnail_path, created_at, storage_backend FROM files WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.ChannelID,
		&i.Filename,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.ThumbnailPath,
		&i.CreatedAt,
		&i.StorageBackend,
	)
	return i, err
}

const listFilesByChannel = `-- name: ListFilesByChannel :many
SELECT id, message_id, user_id, channel_id, filename, original_name, mime_type, size_bytes, storage_path, thumbnail_path, created_at, storage_backend FROM files WHERE channel_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListFilesByChannelParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListFilesByChannel(ctx context.Context, arg ListFilesByChannelParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByChannel, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.ChannelID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.CreatedAt,
			&i.StorageBackend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByMessage = `-- name: ListFilesByMessage :many
SELECT id, message_id, user_id, channel_id, filename, original_name, mime_type, size_bytes, storage_path, thumbnail_path, created_at, storage_backend FROM files WHERE message_id = $1
`

func (q *Queries) ListFilesByMessage(ctx context.Context, messageID pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.ChannelID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.CreatedAt,
			&i.StorageBackend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByMessageIDs = `-- name: ListFilesByMessageIDs :many
SELECT id, message_id, user_id, channel_id, filename, original_name, mime_type, size_bytes, storage_path, thumbnail_path, created_at, storage_backend FROM files WHERE message_id = ANY($1::uuid[])
`

func (q *Queries) ListFilesByMessageIDs(ctx context.Context, messageIds []pgtype.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByMessageIDs, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.ChannelID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.CreatedAt,
			&i.StorageBackend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesForStorageMigration = `-- name: ListFilesForStorageMigration :many
SELECT id, message_id, user_id, channel_id, filename, original_name, mime_type, size_bytes, storage_path, thumbnail_path, created_at, storage_backend FROM files
WHERE storage_backend = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListFilesForStorageMigrationParams struct {
	StorageBackend string `json:"storage_backend"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) ListFilesForStorageMigration(ctx context.Context, arg ListFilesForStorageMigrationParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesForStorageMigration, arg.StorageBackend, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.ChannelID,
			&i.Filename,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.ThumbnailPath,
			&i.CreatedAt,
			&i.StorageBackend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileStorageBackend = `-- name: UpdateFileStorageBackend :exec
UPDATE files SET storage_backend = $2 WHERE id = $1
`

type UpdateFileStorageBackendParams struct {
	ID             pgtype.UUID `json:"id"`
	StorageBackend string      `json:"storage_backend"`
}

func (q *Queries) UpdateFileStorageBackend(ctx context.Context, arg UpdateFileStorageBackendParams) error {
	_, err := q.db.Exec(ctx, updateFileStorageBackend, arg.ID, arg.StorageBackend)
	return err
}
