// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMention = `-- name: CreateMention :exec
INSERT INTO mentions (message_id, user_id, channel_id, mention_type) VALUES ($1, $2, $3, $4)
`

type CreateMentionParams struct {
	MessageID   pgtype.UUID `json:"message_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ChannelID   pgtype.UUID `json:"channel_id"`
	MentionType string      `json:"mention_type"`
}

func (q *Queries) CreateMention(ctx context.Context, arg CreateMentionParams) error {
	_, err := q.db.Exec(ctx, createMention,
		arg.MessageID,
		arg.UserID,
		arg.ChannelID,
		arg.MentionType,
	)
	return err
}

const getUnreadMentions = `-- name: GetUnreadMentions :many
SELECT m.id, m.message_id, m.user_id, m.channel_id, m.is_read, m.created_at, m.mention_type, msg.content, msg.channel_id as msg_channel_id, ch.name as channel_name
FROM mentions m
JOIN messages msg ON msg.id = m.message_id
JOIN channels ch ON ch.id = m.channel_id
WHERE m.user_id = $1 AND m.is_read = FALSE
ORDER BY m.created_at DESC
`

type GetUnreadMentionsRow struct {
	ID           pgtype.UUID        `json:"id"`
	MessageID    pgtype.UUID        `json:"message_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ChannelID    pgtype.UUID        `json:"channel_id"`
	IsRead       bool               `json:"is_read"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	MentionType  string             `json:"mention_type"`
	Content      string             `json:"content"`
	MsgChannelID pgtype.UUID        `json:"msg_channel_id"`
	ChannelName  string             `json:"channel_name"`
}

func (q *Queries) GetUnreadMentions(ctx context.Context, userID pgtype.UUID) ([]GetUnreadMentionsRow, error) {
	rows, err := q.db.Query(ctx, getUnreadMentions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnreadMentionsRow{}
	for rows.Next() {
		var i GetUnreadMentionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.ChannelID,
			&i.IsRead,
			&i.CreatedAt,
			&i.MentionType,
			&i.Content,
			&i.MsgChannelID,
			&i.ChannelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMentionsRead = `-- name: MarkMentionsRead :exec
UPDATE mentions SET is_read = TRUE WHERE user_id = $1 AND channel_id = $2
`

type MarkMentionsReadParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

func (q *Queries) MarkMentionsRead(ctx context.Context, arg MarkMentionsReadParams) error {
	_, err := q.db.Exec(ctx, markMentionsRead, arg.UserID, arg.ChannelID)
	return err
}
