// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: messages.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (channel_id, user_id, thread_id, content, content_type, metadata)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, channel_id, user_id, thread_id, content, content_type, edited_at, is_pinned, metadata, search_vector, created_at, updated_at, original_content, rc_message_id
`

type CreateMessageParams struct {
	ChannelID   pgtype.UUID     `json:"channel_id"`
	UserID      pgtype.UUID     `json:"user_id"`
	ThreadID    pgtype.UUID     `json:"thread_id"`
	Content     string          `json:"content"`
	ContentType string          `json:"content_type"`
	Metadata    json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChannelID,
		arg.UserID,
		arg.ThreadID,
		arg.Content,
		arg.ContentType,
		arg.Metadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.ThreadID,
		&i.Content,
		&i.ContentType,
		&i.EditedAt,
		&i.IsPinned,
		&i.Metadata,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalContent,
		&i.RcMessageID,
	)
	return i, err
}

const createMessageWithRCID = `-- name: CreateMessageWithRCID :one
INSERT INTO messages (channel_id, user_id, thread_id, content, content_type, metadata, rc_message_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, channel_id, user_id, thread_id, content, content_type, edited_at, is_pinned, metadata, search_vector, created_at, updated_at, original_content, rc_message_id
`

type CreateMessageWithRCIDParams struct {
	ChannelID   pgtype.UUID        `json:"channel_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ThreadID    pgtype.UUID        `json:"thread_id"`
	Content     string             `json:"content"`
	ContentType string             `json:"content_type"`
	Metadata    json.RawMessage    `json:"metadata"`
	RcMessageID pgtype.Text        `json:"rc_message_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMessageWithRCID(ctx context.Context, arg CreateMessageWithRCIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessageWithRCID,
		arg.ChannelID,
		arg.UserID,
		arg.ThreadID,
		arg.Content,
		arg.ContentType,
		arg.Metadata,
		arg.RcMessageID,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.ThreadID,
		&i.Content,
		&i.ContentType,
		&i.EditedAt,
		&i.IsPinned,
		&i.Metadata,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalContent,
		&i.RcMessageID,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const deleteMessageByRCID = `-- name: DeleteMessageByRCID :exec
DELETE FROM messages WHERE rc_message_id = $1
`

func (q *Queries) DeleteMessageByRCID(ctx context.Context, rcMessageID pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteMessageByRCID, rcMessageID)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, m.original_content, m.rc_message_id, u.username, u.display_name, u.avatar_url, u.is_bot
FROM messages m JOIN users u ON u.id = m.user_id
WHERE m.id = $1
`

type GetMessageByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ThreadID        pgtype.UUID        `json:"thread_id"`
	Content         string             `json:"content"`
	ContentType     string             `json:"content_type"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	IsPinned        bool               `json:"is_pinned"`
	Metadata        json.RawMessage    `json:"metadata"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OriginalContent pgtype.Text        `json:"original_content"`
	RcMessageID     pgtype.Text        `json:"rc_message_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsBot           bool               `json:"is_bot"`
}

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.ThreadID,
		&i.Content,
		&i.ContentType,
		&i.EditedAt,
		&i.IsPinned,
		&i.Metadata,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalContent,
		&i.RcMessageID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsBot,
	)
	return i, err
}

const getMessageByRCID = `-- name: GetMessageByRCID :one
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, m.original_content, m.rc_message_id, u.username, u.display_name, u.avatar_url, u.is_bot
FROM messages m JOIN users u ON u.id = m.user_id
WHERE m.rc_message_id = $1
`

type GetMessageByRCIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ThreadID        pgtype.UUID        `json:"thread_id"`
	Content         string             `json:"content"`
	ContentType     string             `json:"content_type"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	IsPinned        bool               `json:"is_pinned"`
	Metadata        json.RawMessage    `json:"metadata"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OriginalContent pgtype.Text        `json:"original_content"`
	RcMessageID     pgtype.Text        `json:"rc_message_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsBot           bool               `json:"is_bot"`
}

func (q *Queries) GetMessageByRCID(ctx context.Context, rcMessageID pgtype.Text) (GetMessageByRCIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByRCID, rcMessageID)
	var i GetMessageByRCIDRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.ThreadID,
		&i.Content,
		&i.ContentType,
		&i.EditedAt,
		&i.IsPinned,
		&i.Metadata,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalContent,
		&i.RcMessageID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.IsBot,
	)
	return i, err
}

const getMessagesSince = `-- name: GetMessagesSince :many
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, m.original_content, m.rc_message_id, u.username, u.display_name, u.avatar_url, u.is_bot
FROM messages m JOIN users u ON u.id = m.user_id
WHERE m.channel_id = $1 AND m.created_at > $2
ORDER BY m.created_at ASC
`

type GetMessagesSinceParams struct {
	ChannelID pgtype.UUID        `json:"channel_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetMessagesSinceRow struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ThreadID        pgtype.UUID        `json:"thread_id"`
	Content         string             `json:"content"`
	ContentType     string             `json:"content_type"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	IsPinned        bool               `json:"is_pinned"`
	Metadata        json.RawMessage    `json:"metadata"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OriginalContent pgtype.Text        `json:"original_content"`
	RcMessageID     pgtype.Text        `json:"rc_message_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsBot           bool               `json:"is_bot"`
}

func (q *Queries) GetMessagesSince(ctx context.Context, arg GetMessagesSinceParams) ([]GetMessagesSinceRow, error) {
	rows, err := q.db.Query(ctx, getMessagesSince, arg.ChannelID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesSinceRow{}
	for rows.Next() {
		var i GetMessagesSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ThreadID,
			&i.Content,
			&i.ContentType,
			&i.EditedAt,
			&i.IsPinned,
			&i.Metadata,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalContent,
			&i.RcMessageID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMessages = `-- name: ListChannelMessages :many
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, m.original_content, m.rc_message_id, u.username, u.display_name, u.avatar_url, u.is_bot
FROM messages m JOIN users u ON u.id = m.user_id
WHERE m.channel_id = $1 AND m.thread_id IS NULL
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListChannelMessagesParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListChannelMessagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ThreadID        pgtype.UUID        `json:"thread_id"`
	Content         string             `json:"content"`
	ContentType     string             `json:"content_type"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	IsPinned        bool               `json:"is_pinned"`
	Metadata        json.RawMessage    `json:"metadata"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OriginalContent pgtype.Text        `json:"original_content"`
	RcMessageID     pgtype.Text        `json:"rc_message_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsBot           bool               `json:"is_bot"`
}

func (q *Queries) ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]ListChannelMessagesRow, error) {
	rows, err := q.db.Query(ctx, listChannelMessages, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelMessagesRow{}
	for rows.Next() {
		var i ListChannelMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ThreadID,
			&i.Content,
			&i.ContentType,
			&i.EditedAt,
			&i.IsPinned,
			&i.Metadata,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalContent,
			&i.RcMessageID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMessages = `-- name: ListPinnedMessages :many
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, m.original_content, m.rc_message_id, u.username, u.display_name, u.avatar_url, u.is_bot
FROM messages m JOIN users u ON u.id = m.user_id
WHERE m.channel_id = $1 AND m.is_pinned = TRUE
ORDER BY m.created_at DESC
`

type ListPinnedMessagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ThreadID        pgtype.UUID        `json:"thread_id"`
	Content         string             `json:"content"`
	ContentType     string             `json:"content_type"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	IsPinned        bool               `json:"is_pinned"`
	Metadata        json.RawMessage    `json:"metadata"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OriginalContent pgtype.Text        `json:"original_content"`
	RcMessageID     pgtype.Text        `json:"rc_message_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsBot           bool               `json:"is_bot"`
}

func (q *Queries) ListPinnedMessages(ctx context.Context, channelID pgtype.UUID) ([]ListPinnedMessagesRow, error) {
	rows, err := q.db.Query(ctx, listPinnedMessages, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPinnedMessagesRow{}
	for rows.Next() {
		var i ListPinnedMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ThreadID,
			&i.Content,
			&i.ContentType,
			&i.EditedAt,
			&i.IsPinned,
			&i.Metadata,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalContent,
			&i.RcMessageID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessages = `-- name: ListThreadMessages :many
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, m.original_content, m.rc_message_id, u.username, u.display_name, u.avatar_url, u.is_bot
FROM messages m JOIN users u ON u.id = m.user_id
WHERE m.thread_id = $1
ORDER BY m.created_at ASC
`

type ListThreadMessagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ThreadID        pgtype.UUID        `json:"thread_id"`
	Content         string             `json:"content"`
	ContentType     string             `json:"content_type"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	IsPinned        bool               `json:"is_pinned"`
	Metadata        json.RawMessage    `json:"metadata"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OriginalContent pgtype.Text        `json:"original_content"`
	RcMessageID     pgtype.Text        `json:"rc_message_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsBot           bool               `json:"is_bot"`
}

func (q *Queries) ListThreadMessages(ctx context.Context, threadID pgtype.UUID) ([]ListThreadMessagesRow, error) {
	rows, err := q.db.Query(ctx, listThreadMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListThreadMessagesRow{}
	for rows.Next() {
		var i ListThreadMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ThreadID,
			&i.Content,
			&i.ContentType,
			&i.EditedAt,
			&i.IsPinned,
			&i.Metadata,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalContent,
			&i.RcMessageID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinMessage = `-- name: PinMessage :exec
UPDATE messages SET is_pinned = TRUE WHERE id = $1
`

func (q *Queries) PinMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pinMessage, id)
	return err
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, m.original_content, m.rc_message_id, u.username, u.display_name, u.avatar_url, u.is_bot,
       ts_rank(m.search_vector, websearch_to_tsquery('portuguese', unaccent($1))) AS rank
FROM messages m JOIN users u ON u.id = m.user_id
WHERE m.search_vector @@ websearch_to_tsquery('portuguese', unaccent($1))
  AND ($2::uuid IS NULL OR m.channel_id = $2)
ORDER BY rank DESC
LIMIT $3 OFFSET $4
`

type SearchMessagesParams struct {
	Unaccent string      `json:"unaccent"`
	Column2  pgtype.UUID `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type SearchMessagesRow struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ThreadID        pgtype.UUID        `json:"thread_id"`
	Content         string             `json:"content"`
	ContentType     string             `json:"content_type"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	IsPinned        bool               `json:"is_pinned"`
	Metadata        json.RawMessage    `json:"metadata"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OriginalContent pgtype.Text        `json:"original_content"`
	RcMessageID     pgtype.Text        `json:"rc_message_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsBot           bool               `json:"is_bot"`
	Rank            float32            `json:"rank"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages,
		arg.Unaccent,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ThreadID,
			&i.Content,
			&i.ContentType,
			&i.EditedAt,
			&i.IsPinned,
			&i.Metadata,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalContent,
			&i.RcMessageID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsBot,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMessagesForUser = `-- name: SearchMessagesForUser :many
SELECT m.id, m.channel_id, m.user_id, m.thread_id, m.content, m.content_type, m.edited_at, m.is_pinned, m.metadata, m.search_vector, m.created_at, m.updated_at, m.original_content, m.rc_message_id, u.username, u.display_name, u.avatar_url, u.is_bot,
       ts_rank(m.search_vector, websearch_to_tsquery('portuguese', unaccent($1))) AS rank
FROM messages m
JOIN users u ON u.id = m.user_id
JOIN channel_members cm ON cm.channel_id = m.channel_id AND cm.user_id = $3
WHERE m.search_vector @@ websearch_to_tsquery('portuguese', unaccent($1))
  AND ($2::uuid IS NULL OR m.channel_id = $2)
ORDER BY rank DESC
LIMIT $4 OFFSET $5
`

type SearchMessagesForUserParams struct {
	Unaccent string      `json:"unaccent"`
	Column2  pgtype.UUID `json:"column_2"`
	UserID   pgtype.UUID `json:"user_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type SearchMessagesForUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ThreadID        pgtype.UUID        `json:"thread_id"`
	Content         string             `json:"content"`
	ContentType     string             `json:"content_type"`
	EditedAt        pgtype.Timestamptz `json:"edited_at"`
	IsPinned        bool               `json:"is_pinned"`
	Metadata        json.RawMessage    `json:"metadata"`
	SearchVector    interface{}        `json:"search_vector"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	OriginalContent pgtype.Text        `json:"original_content"`
	RcMessageID     pgtype.Text        `json:"rc_message_id"`
	Username        string             `json:"username"`
	DisplayName     string             `json:"display_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	IsBot           bool               `json:"is_bot"`
	Rank            float32            `json:"rank"`
}

func (q *Queries) SearchMessagesForUser(ctx context.Context, arg SearchMessagesForUserParams) ([]SearchMessagesForUserRow, error) {
	rows, err := q.db.Query(ctx, searchMessagesForUser,
		arg.Unaccent,
		arg.Column2,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesForUserRow{}
	for rows.Next() {
		var i SearchMessagesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.ThreadID,
			&i.Content,
			&i.ContentType,
			&i.EditedAt,
			&i.IsPinned,
			&i.Metadata,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalContent,
			&i.RcMessageID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.IsBot,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unpinMessage = `-- name: UnpinMessage :exec
UPDATE messages SET is_pinned = FALSE WHERE id = $1
`

func (q *Queries) UnpinMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unpinMessage, id)
	return err
}

const updateMessageByRCID = `-- name: UpdateMessageByRCID :one
UPDATE messages SET
  original_content = CASE WHEN original_content IS NULL THEN content ELSE original_content END,
  content = $2,
  edited_at = $3
WHERE rc_message_id = $1 RETURNING id, channel_id, user_id, thread_id, content, content_type, edited_at, is_pinned, metadata, search_vector, created_at, updated_at, original_content, rc_message_id
`

type UpdateMessageByRCIDParams struct {
	RcMessageID pgtype.Text        `json:"rc_message_id"`
	Content     string             `json:"content"`
	EditedAt    pgtype.Timestamptz `json:"edited_at"`
}

func (q *Queries) UpdateMessageByRCID(ctx context.Context, arg UpdateMessageByRCIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageByRCID, arg.RcMessageID, arg.Content, arg.EditedAt)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.ThreadID,
		&i.Content,
		&i.ContentType,
		&i.EditedAt,
		&i.IsPinned,
		&i.Metadata,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalContent,
		&i.RcMessageID,
	)
	return i, err
}

const updateMessageContent = `-- name: UpdateMessageContent :one
UPDATE messages SET
  original_content = CASE WHEN original_content IS NULL THEN content ELSE original_content END,
  content = $2,
  edited_at = NOW()
WHERE id = $1 RETURNING id, channel_id, user_id, thread_id, content, content_type, edited_at, is_pinned, metadata, search_vector, created_at, updated_at, original_content, rc_message_id
`

type UpdateMessageContentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContent, arg.ID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.UserID,
		&i.ThreadID,
		&i.Content,
		&i.ContentType,
		&i.EditedAt,
		&i.IsPinned,
		&i.Metadata,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalContent,
		&i.RcMessageID,
	)
	return i, err
}

const updateMessageRCID = `-- name: UpdateMessageRCID :exec
UPDATE messages SET rc_message_id = $2 WHERE id = $1
`

type UpdateMessageRCIDParams struct {
	ID          pgtype.UUID `json:"id"`
	RcMessageID pgtype.Text `json:"rc_message_id"`
}

func (q *Queries) UpdateMessageRCID(ctx context.Context, arg UpdateMessageRCIDParams) error {
	_, err := q.db.Exec(ctx, updateMessageRCID, arg.ID, arg.RcMessageID)
	return err
}
