// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: migration.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMigrationLogs = `-- name: CountMigrationLogs :one
SELECT COUNT(*) FROM migration_logs WHERE job_id = $1
`

func (q *Queries) CountMigrationLogs(ctx context.Context, jobID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMigrationLogs, jobID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMigrationJob = `-- name: CreateMigrationJob :one
INSERT INTO migration_jobs (status, config, started_by)
VALUES ($1, $2, $3)
RETURNING id, status, config, started_by, phase, progress, error, started_at, completed_at, created_at, updated_at
`

type CreateMigrationJobParams struct {
	Status    string      `json:"status"`
	Config    []byte      `json:"config"`
	StartedBy pgtype.UUID `json:"started_by"`
}

func (q *Queries) CreateMigrationJob(ctx context.Context, arg CreateMigrationJobParams) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, createMigrationJob, arg.Status, arg.Config, arg.StartedBy)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Config,
		&i.StartedBy,
		&i.Phase,
		&i.Progress,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMigrationLog = `-- name: CreateMigrationLog :one
INSERT INTO migration_logs (job_id, level, phase, message, detail)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type CreateMigrationLogParams struct {
	JobID   pgtype.UUID     `json:"job_id"`
	Level   string          `json:"level"`
	Phase   string          `json:"phase"`
	Message string          `json:"message"`
	Detail  json.RawMessage `json:"detail"`
}

type CreateMigrationLogRow struct {
	ID        int64              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateMigrationLog(ctx context.Context, arg CreateMigrationLogParams) (CreateMigrationLogRow, error) {
	row := q.db.QueryRow(ctx, createMigrationLog,
		arg.JobID,
		arg.Level,
		arg.Phase,
		arg.Message,
		arg.Detail,
	)
	var i CreateMigrationLogRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getLatestMigrationJob = `-- name: GetLatestMigrationJob :one
SELECT id, status, config, started_by, phase, progress, error, started_at, completed_at, created_at, updated_at FROM migration_jobs ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestMigrationJob(ctx context.Context) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, getLatestMigrationJob)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Config,
		&i.StartedBy,
		&i.Phase,
		&i.Progress,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationJob = `-- name: GetMigrationJob :one
SELECT id, status, config, started_by, phase, progress, error, started_at, completed_at, created_at, updated_at FROM migration_jobs WHERE id = $1
`

func (q *Queries) GetMigrationJob(ctx context.Context, id pgtype.UUID) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, getMigrationJob, id)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Config,
		&i.StartedBy,
		&i.Phase,
		&i.Progress,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationRoomState = `-- name: GetMigrationRoomState :one
SELECT rc_room_id, rc_room_name, rc_room_type, message_count, latest_export, job_id, updated_at FROM migration_room_state WHERE rc_room_id = $1
`

func (q *Queries) GetMigrationRoomState(ctx context.Context, rcRoomID string) (MigrationRoomState, error) {
	row := q.db.QueryRow(ctx, getMigrationRoomState, rcRoomID)
	var i MigrationRoomState
	err := row.Scan(
		&i.RcRoomID,
		&i.RcRoomName,
		&i.RcRoomType,
		&i.MessageCount,
		&i.LatestExport,
		&i.JobID,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunningMigrationJob = `-- name: GetRunningMigrationJob :one
SELECT id, status, config, started_by, phase, progress, error, started_at, completed_at, created_at, updated_at FROM migration_jobs WHERE status = 'running' LIMIT 1
`

func (q *Queries) GetRunningMigrationJob(ctx context.Context) (MigrationJob, error) {
	row := q.db.QueryRow(ctx, getRunningMigrationJob)
	var i MigrationJob
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Config,
		&i.StartedBy,
		&i.Phase,
		&i.Progress,
		&i.Error,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMigrationJobs = `-- name: ListMigrationJobs :many
SELECT id, status, config, started_by, phase, progress, error, started_at, completed_at, created_at, updated_at FROM migration_jobs ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListMigrationJobs(ctx context.Context, limit int32) ([]MigrationJob, error) {
	rows, err := q.db.Query(ctx, listMigrationJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigrationJob{}
	for rows.Next() {
		var i MigrationJob
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Config,
			&i.StartedBy,
			&i.Phase,
			&i.Progress,
			&i.Error,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationLogs = `-- name: ListMigrationLogs :many
SELECT id, job_id, level, phase, message, detail, created_at FROM migration_logs
WHERE job_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type ListMigrationLogsParams struct {
	JobID pgtype.UUID `json:"job_id"`
	ID    int64       `json:"id"`
	Limit int32       `json:"limit"`
}

func (q *Queries) ListMigrationLogs(ctx context.Context, arg ListMigrationLogsParams) ([]MigrationLog, error) {
	rows, err := q.db.Query(ctx, listMigrationLogs, arg.JobID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigrationLog{}
	for rows.Next() {
		var i MigrationLog
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Level,
			&i.Phase,
			&i.Message,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMigrationRoomStates = `-- name: ListMigrationRoomStates :many
SELECT rc_room_id, rc_room_name, rc_room_type, message_count, latest_export, job_id, updated_at FROM migration_room_state ORDER BY rc_room_name
`

func (q *Queries) ListMigrationRoomStates(ctx context.Context) ([]MigrationRoomState, error) {
	rows, err := q.db.Query(ctx, listMigrationRoomStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigrationRoomState{}
	for rows.Next() {
		var i MigrationRoomState
		if err := rows.Scan(
			&i.RcRoomID,
			&i.RcRoomName,
			&i.RcRoomType,
			&i.MessageCount,
			&i.LatestExport,
			&i.JobID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMigrationJobPhase = `-- name: UpdateMigrationJobPhase :exec
UPDATE migration_jobs
SET phase = $2, progress = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateMigrationJobPhaseParams struct {
	ID       pgtype.UUID `json:"id"`
	Phase    string      `json:"phase"`
	Progress []byte      `json:"progress"`
}

func (q *Queries) UpdateMigrationJobPhase(ctx context.Context, arg UpdateMigrationJobPhaseParams) error {
	_, err := q.db.Exec(ctx, updateMigrationJobPhase, arg.ID, arg.Phase, arg.Progress)
	return err
}

const updateMigrationJobStatus = `-- name: UpdateMigrationJobStatus :exec
UPDATE migration_jobs
SET status = $2, error = $3, updated_at = NOW(),
    started_at = CASE WHEN $2 = 'running' AND started_at IS NULL THEN NOW() ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed', 'cancelled') THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateMigrationJobStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
	Error  string      `json:"error"`
}

func (q *Queries) UpdateMigrationJobStatus(ctx context.Context, arg UpdateMigrationJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateMigrationJobStatus, arg.ID, arg.Status, arg.Error)
	return err
}

const upsertMigrationRoomState = `-- name: UpsertMigrationRoomState :exec
INSERT INTO migration_room_state (rc_room_id, rc_room_name, rc_room_type, message_count, latest_export, job_id, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
ON CONFLICT (rc_room_id) DO UPDATE SET
    rc_room_name = EXCLUDED.rc_room_name,
    message_count = migration_room_state.message_count + EXCLUDED.message_count,
    latest_export = EXCLUDED.latest_export,
    job_id = EXCLUDED.job_id,
    updated_at = NOW()
`

type UpsertMigrationRoomStateParams struct {
	RcRoomID     string             `json:"rc_room_id"`
	RcRoomName   string             `json:"rc_room_name"`
	RcRoomType   string             `json:"rc_room_type"`
	MessageCount int32              `json:"message_count"`
	LatestExport pgtype.Timestamptz `json:"latest_export"`
	JobID        pgtype.UUID        `json:"job_id"`
}

func (q *Queries) UpsertMigrationRoomState(ctx context.Context, arg UpsertMigrationRoomStateParams) error {
	_, err := q.db.Exec(ctx, upsertMigrationRoomState,
		arg.RcRoomID,
		arg.RcRoomName,
		arg.RcRoomType,
		arg.MessageCount,
		arg.LatestExport,
		arg.JobID,
	)
	return err
}
