// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                pgtype.UUID        `json:"user_id"`
	Slug                  string             `json:"slug"`
	Name                  string             `json:"name"`
	Emoji                 pgtype.Text        `json:"emoji"`
	AvatarUrl             pgtype.Text        `json:"avatar_url"`
	Description           pgtype.Text        `json:"description"`
	Scope                 pgtype.Text        `json:"scope"`
	Status                string             `json:"status"`
	GatewayUrl            string             `json:"gateway_url"`
	GatewayToken          pgtype.Text        `json:"gateway_token"`
	Model                 string             `json:"model"`
	SystemPrompt          pgtype.Text        `json:"system_prompt"`
	MaxTokens             int32              `json:"max_tokens"`
	Temperature           float32            `json:"temperature"`
	BridgeUrl             pgtype.Text        `json:"bridge_url"`
	UseBridge             bool               `json:"use_bridge"`
	MaxContextMessages    int32              `json:"max_context_messages"`
	AutoJoinChannels      []string           `json:"auto_join_channels"`
	Capabilities          json.RawMessage    `json:"capabilities"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	RespondWithoutMention bool               `json:"respond_without_mention"`
	Category              string             `json:"category"`
}

type AgentSession struct {
	ID        pgtype.UUID        `json:"id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Title     pgtype.Text        `json:"title"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AgentUsage struct {
	ID             pgtype.UUID        `json:"id"`
	AgentID        pgtype.UUID        `json:"agent_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	SessionID      pgtype.UUID        `json:"session_id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	InputTokens    int32              `json:"input_tokens"`
	OutputTokens   int32              `json:"output_tokens"`
	CostUsd        pgtype.Numeric     `json:"cost_usd"`
	ResponseTimeMs int32              `json:"response_time_ms"`
	ModelUsed      pgtype.Text        `json:"model_used"`
	Source         pgtype.Text        `json:"source"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ApiToken struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Scopes      []string           `json:"scopes"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	IsRevoked   bool               `json:"is_revoked"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AppConfig struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

type Channel struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	Description   pgtype.Text        `json:"description"`
	Type          string             `json:"type"`
	Topic         pgtype.Text        `json:"topic"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	IsArchived    bool               `json:"is_archived"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ReadOnly      bool               `json:"read_only"`
	RetentionDays pgtype.Int4        `json:"retention_days"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
}

type ChannelMember struct {
	ChannelID     pgtype.UUID        `json:"channel_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Role          string             `json:"role"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
	LastReadMsgID pgtype.UUID        `json:"last_read_msg_id"`
	Muted         bool               `json:"muted"`
	Notifications string             `json:"notifications"`
	Hidden        bool               `json:"hidden"`
	SectionID     pgtype.UUID        `json:"section_id"`
	IsPinned      bool               `json:"is_pinned"`
}

type ChannelWebhook struct {
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Name      string             `json:"name"`
	Token     string             `json:"token"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CustomEmoji struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Aliases     []string           `json:"aliases"`
	MimeType    string             `json:"mime_type"`
	StoragePath string             `json:"storage_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID             pgtype.UUID        `json:"id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	Filename       string             `json:"filename"`
	OriginalName   string             `json:"original_name"`
	MimeType       string             `json:"mime_type"`
	SizeBytes      int64              `json:"size_bytes"`
	StoragePath    string             `json:"storage_path"`
	ThumbnailPath  pgtype.Text        `json:"thumbnail_path"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StorageBackend string             `json:"storage_backend"`
}

type Mention struct {
	ID          pgtype.UUID        `json:"id"`
	MessageID   pgtype.UUID        `json:"message_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ChannelID   pgtype.UUID        `json:"channel_id"`
	IsRead      bool               `json:"is_read"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MentionType string             `json:"mention_type"`
}

type Message struct {
	ID           pgtype.UUID        `json:"id"`
	ChannelID    pgtype.UUID        `json:"channel_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ThreadID     pgtype.UUID        `json:"thread_id"`
	Content      string             `json:"content"`
	ContentType  string             `json:"content_type"`
	EditedAt     pgtype.Timestamptz `json:"edited_at"`
	IsPinned     bool               `json:"is_pinned"`
	Metadata     json.RawMessage    `json:"metadata"`
	SearchVector interface{}        `json:"search_vector"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type MessageAuditLog struct {
	ID               pgtype.UUID        `json:"id"`
	ChannelID        pgtype.UUID        `json:"channel_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	MessageCreatedAt pgtype.Timestamptz `json:"message_created_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy        string             `json:"deleted_by"`
}

type MigrationJob struct {
	ID          pgtype.UUID        `json:"id"`
	Status      string             `json:"status"`
	Config      []byte             `json:"config"`
	StartedBy   pgtype.UUID        `json:"started_by"`
	Phase       string             `json:"phase"`
	Progress    []byte             `json:"progress"`
	Error       string             `json:"error"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MigrationLog struct {
	ID        int64              `json:"id"`
	JobID     pgtype.UUID        `json:"job_id"`
	Level     string             `json:"level"`
	Phase     string             `json:"phase"`
	Message   string             `json:"message"`
	Detail    json.RawMessage    `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MigrationRoomState struct {
	RcRoomID     string             `json:"rc_room_id"`
	RcRoomName   string             `json:"rc_room_name"`
	RcRoomType   string             `json:"rc_room_type"`
	MessageCount int32              `json:"message_count"`
	LatestExport pgtype.Timestamptz `json:"latest_export"`
	JobID        pgtype.UUID        `json:"job_id"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Reaction struct {
	MessageID pgtype.UUID        `json:"message_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Emoji     string             `json:"emoji"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SidebarSection struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ThreadSummary struct {
	MessageID      pgtype.UUID        `json:"message_id"`
	ReplyCount     int32              `json:"reply_count"`
	LastReplyAt    pgtype.Timestamptz `json:"last_reply_at"`
	ParticipantIds []pgtype.UUID      `json:"participant_ids"`
}

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	DisplayName   string             `json:"display_name"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	PasswordHash  string             `json:"password_hash"`
	Role          string             `json:"role"`
	Status        string             `json:"status"`
	LastSeen      pgtype.Timestamptz `json:"last_seen"`
	IsBot         bool               `json:"is_bot"`
	BotConfig     json.RawMessage    `json:"bot_config"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	IsDeactivated bool               `json:"is_deactivated"`
	AutoHideDays  int32              `json:"auto_hide_days"`
	ChannelSort   string             `json:"channel_sort"`
	RcUserID      pgtype.Text        `json:"rc_user_id"`
}
