// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: rc_bridge.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRCSyncCursorsForUser = `-- name: DeleteRCSyncCursorsForUser :exec
DELETE FROM rc_sync_cursor WHERE user_id = $1
`

func (q *Queries) DeleteRCSyncCursorsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRCSyncCursorsForUser, userID)
	return err
}

const getRCSyncCursor = `-- name: GetRCSyncCursor :one
SELECT last_seen_ts FROM rc_sync_cursor WHERE user_id = $1 AND rc_room_id = $2
`

type GetRCSyncCursorParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	RcRoomID string      `json:"rc_room_id"`
}

func (q *Queries) GetRCSyncCursor(ctx context.Context, arg GetRCSyncCursorParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getRCSyncCursor, arg.UserID, arg.RcRoomID)
	var last_seen_ts pgtype.Timestamptz
	err := row.Scan(&last_seen_ts)
	return last_seen_ts, err
}

const upsertRCSyncCursor = `-- name: UpsertRCSyncCursor :exec
INSERT INTO rc_sync_cursor (user_id, rc_room_id, last_seen_ts)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, rc_room_id) DO UPDATE SET last_seen_ts = EXCLUDED.last_seen_ts
`

type UpsertRCSyncCursorParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	RcRoomID   string             `json:"rc_room_id"`
	LastSeenTs pgtype.Timestamptz `json:"last_seen_ts"`
}

func (q *Queries) UpsertRCSyncCursor(ctx context.Context, arg UpsertRCSyncCursorParams) error {
	_, err := q.db.Exec(ctx, upsertRCSyncCursor, arg.UserID, arg.RcRoomID, arg.LastSeenTs)
	return err
}
