// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reactions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReaction = `-- name: AddReaction :exec
INSERT INTO reactions (message_id, user_id, emoji) VALUES ($1, $2, $3) ON CONFLICT DO NOTHING
`

type AddReactionParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.Exec(ctx, addReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const getReactionsForMessages = `-- name: GetReactionsForMessages :many
SELECT r.message_id, r.emoji, r.user_id, u.username
FROM reactions r JOIN users u ON u.id = r.user_id
WHERE r.message_id = ANY($1::uuid[])
`

type GetReactionsForMessagesRow struct {
	MessageID pgtype.UUID `json:"message_id"`
	Emoji     string      `json:"emoji"`
	UserID    pgtype.UUID `json:"user_id"`
	Username  string      `json:"username"`
}

func (q *Queries) GetReactionsForMessages(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetReactionsForMessagesRow, error) {
	rows, err := q.db.Query(ctx, getReactionsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReactionsForMessagesRow{}
	for rows.Next() {
		var i GetReactionsForMessagesRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Emoji,
			&i.UserID,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionsByMessage = `-- name: ListReactionsByMessage :many
SELECT r.emoji, r.user_id, u.username, u.display_name
FROM reactions r JOIN users u ON u.id = r.user_id
WHERE r.message_id = $1
ORDER BY r.created_at
`

type ListReactionsByMessageRow struct {
	Emoji       string      `json:"emoji"`
	UserID      pgtype.UUID `json:"user_id"`
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) ListReactionsByMessage(ctx context.Context, messageID pgtype.UUID) ([]ListReactionsByMessageRow, error) {
	rows, err := q.db.Query(ctx, listReactionsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReactionsByMessageRow{}
	for rows.Next() {
		var i ListReactionsByMessageRow
		if err := rows.Scan(
			&i.Emoji,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReaction = `-- name: RemoveReaction :exec
DELETE FROM reactions WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type RemoveReactionParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Emoji     string      `json:"emoji"`
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) error {
	_, err := q.db.Exec(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}
