// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: retention.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredMessages = `-- name: DeleteExpiredMessages :many
DELETE FROM messages
WHERE channel_id = $1
  AND created_at < $2::timestamptz
  AND thread_id IS NULL
RETURNING id, channel_id, user_id, created_at
`

type DeleteExpiredMessagesParams struct {
	ChannelID pgtype.UUID        `json:"channel_id"`
	Column2   pgtype.Timestamptz `json:"column_2"`
}

type DeleteExpiredMessagesRow struct {
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) DeleteExpiredMessages(ctx context.Context, arg DeleteExpiredMessagesParams) ([]DeleteExpiredMessagesRow, error) {
	rows, err := q.db.Query(ctx, deleteExpiredMessages, arg.ChannelID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeleteExpiredMessagesRow{}
	for rows.Next() {
		var i DeleteExpiredMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO message_audit_log (channel_id, user_id, message_created_at, deleted_at, deleted_by)
VALUES ($1, $2, $3, NOW(), $4)
`

type InsertAuditLogParams struct {
	ChannelID        pgtype.UUID        `json:"channel_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	MessageCreatedAt pgtype.Timestamptz `json:"message_created_at"`
	DeletedBy        string             `json:"deleted_by"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ChannelID,
		arg.UserID,
		arg.MessageCreatedAt,
		arg.DeletedBy,
	)
	return err
}

const listChannelsWithRetention = `-- name: ListChannelsWithRetention :many
SELECT id, retention_days FROM channels WHERE is_archived = FALSE
`

type ListChannelsWithRetentionRow struct {
	ID            pgtype.UUID `json:"id"`
	RetentionDays pgtype.Int4 `json:"retention_days"`
}

func (q *Queries) ListChannelsWithRetention(ctx context.Context) ([]ListChannelsWithRetentionRow, error) {
	rows, err := q.db.Query(ctx, listChannelsWithRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelsWithRetentionRow{}
	for rows.Next() {
		var i ListChannelsWithRetentionRow
		if err := rows.Scan(&i.ID, &i.RetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
