// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sidebar_sections.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSidebarSection = `-- name: CreateSidebarSection :one
INSERT INTO sidebar_sections (user_id, name, position)
VALUES ($1, $2, COALESCE((SELECT MAX(position) + 1 FROM sidebar_sections WHERE user_id = $1), 0))
RETURNING id, user_id, name, position, created_at
`

type CreateSidebarSectionParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateSidebarSection(ctx context.Context, arg CreateSidebarSectionParams) (SidebarSection, error) {
	row := q.db.QueryRow(ctx, createSidebarSection, arg.UserID, arg.Name)
	var i SidebarSection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSidebarSection = `-- name: DeleteSidebarSection :exec
DELETE FROM sidebar_sections WHERE id = $1 AND user_id = $2
`

type DeleteSidebarSectionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSidebarSection(ctx context.Context, arg DeleteSidebarSectionParams) error {
	_, err := q.db.Exec(ctx, deleteSidebarSection, arg.ID, arg.UserID)
	return err
}

const getSidebarSection = `-- name: GetSidebarSection :one
SELECT id, user_id, name, position, created_at FROM sidebar_sections WHERE id = $1 AND user_id = $2
`

type GetSidebarSectionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSidebarSection(ctx context.Context, arg GetSidebarSectionParams) (SidebarSection, error) {
	row := q.db.QueryRow(ctx, getSidebarSection, arg.ID, arg.UserID)
	var i SidebarSection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listSidebarSections = `-- name: ListSidebarSections :many
SELECT id, user_id, name, position, created_at FROM sidebar_sections WHERE user_id = $1 ORDER BY position
`

func (q *Queries) ListSidebarSections(ctx context.Context, userID pgtype.UUID) ([]SidebarSection, error) {
	rows, err := q.db.Query(ctx, listSidebarSections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SidebarSection{}
	for rows.Next() {
		var i SidebarSection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSidebarSection = `-- name: UpdateSidebarSection :exec
UPDATE sidebar_sections SET name = $2 WHERE id = $1 AND user_id = $3
`

type UpdateSidebarSectionParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateSidebarSection(ctx context.Context, arg UpdateSidebarSectionParams) error {
	_, err := q.db.Exec(ctx, updateSidebarSection, arg.ID, arg.Name, arg.UserID)
	return err
}

const updateSidebarSectionPosition = `-- name: UpdateSidebarSectionPosition :exec
UPDATE sidebar_sections SET position = $2 WHERE id = $1 AND user_id = $3
`

type UpdateSidebarSectionPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	Position int32       `json:"position"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateSidebarSectionPosition(ctx context.Context, arg UpdateSidebarSectionPositionParams) error {
	_, err := q.db.Exec(ctx, updateSidebarSectionPosition, arg.ID, arg.Position, arg.UserID)
	return err
}
