// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: thread_summaries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getThreadSummariesForMessages = `-- name: GetThreadSummariesForMessages :many
SELECT message_id, reply_count, last_reply_at, participant_ids FROM thread_summaries WHERE message_id = ANY($1::uuid[])
`

func (q *Queries) GetThreadSummariesForMessages(ctx context.Context, dollar_1 []pgtype.UUID) ([]ThreadSummary, error) {
	rows, err := q.db.Query(ctx, getThreadSummariesForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadSummary{}
	for rows.Next() {
		var i ThreadSummary
		if err := rows.Scan(
			&i.MessageID,
			&i.ReplyCount,
			&i.LastReplyAt,
			&i.ParticipantIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadSummary = `-- name: GetThreadSummary :one
SELECT message_id, reply_count, last_reply_at, participant_ids FROM thread_summaries WHERE message_id = $1
`

func (q *Queries) GetThreadSummary(ctx context.Context, messageID pgtype.UUID) (ThreadSummary, error) {
	row := q.db.QueryRow(ctx, getThreadSummary, messageID)
	var i ThreadSummary
	err := row.Scan(
		&i.MessageID,
		&i.ReplyCount,
		&i.LastReplyAt,
		&i.ParticipantIds,
	)
	return i, err
}

const upsertThreadSummary = `-- name: UpsertThreadSummary :exec
INSERT INTO thread_summaries (message_id, reply_count, last_reply_at, participant_ids)
VALUES ($1, 1, NOW(), ARRAY[$2::uuid])
ON CONFLICT (message_id) DO UPDATE SET
    reply_count = thread_summaries.reply_count + 1,
    last_reply_at = NOW(),
    participant_ids = CASE
        WHEN $2::uuid = ANY(thread_summaries.participant_ids) THEN thread_summaries.participant_ids
        ELSE array_append(thread_summaries.participant_ids, $2::uuid)
    END
`

type UpsertThreadSummaryParams struct {
	MessageID pgtype.UUID `json:"message_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpsertThreadSummary(ctx context.Context, arg UpsertThreadSummaryParams) error {
	_, err := q.db.Exec(ctx, upsertThreadSummary, arg.MessageID, arg.UserID)
	return err
}
