// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, display_name, password_hash, role, is_bot, bot_config)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, username, email, display_name, avatar_url, password_hash, role, status, last_seen, is_bot, bot_config, created_at, updated_at, is_deactivated, auto_hide_days, channel_sort
`

type CreateUserParams struct {
	Username     string          `json:"username"`
	Email        string          `json:"email"`
	DisplayName  string          `json:"display_name"`
	PasswordHash string          `json:"password_hash"`
	Role         string          `json:"role"`
	IsBot        bool            `json:"is_bot"`
	BotConfig    json.RawMessage `json:"bot_config"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.IsBot,
		arg.BotConfig,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastSeen,
		&i.IsBot,
		&i.BotConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeactivated,
		&i.AutoHideDays,
		&i.ChannelSort,
	)
	return i, err
}

const getAutoHideDays = `-- name: GetAutoHideDays :one
SELECT auto_hide_days FROM users WHERE id = $1
`

func (q *Queries) GetAutoHideDays(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getAutoHideDays, id)
	var auto_hide_days int32
	err := row.Scan(&auto_hide_days)
	return auto_hide_days, err
}

const getChannelSort = `-- name: GetChannelSort :one
SELECT channel_sort FROM users WHERE id = $1
`

func (q *Queries) GetChannelSort(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getChannelSort, id)
	var channel_sort string
	err := row.Scan(&channel_sort)
	return channel_sort, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, avatar_url, password_hash, role, status, last_seen, is_bot, bot_config, created_at, updated_at, is_deactivated, auto_hide_days, channel_sort FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastSeen,
		&i.IsBot,
		&i.BotConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeactivated,
		&i.AutoHideDays,
		&i.ChannelSort,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, avatar_url, password_hash, role, status, last_seen, is_bot, bot_config, created_at, updated_at, is_deactivated, auto_hide_days, channel_sort FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastSeen,
		&i.IsBot,
		&i.BotConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeactivated,
		&i.AutoHideDays,
		&i.ChannelSort,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, avatar_url, password_hash, role, status, last_seen, is_bot, bot_config, created_at, updated_at, is_deactivated, auto_hide_days, channel_sort FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastSeen,
		&i.IsBot,
		&i.BotConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeactivated,
		&i.AutoHideDays,
		&i.ChannelSort,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, display_name, avatar_url, role, status, last_seen, is_bot
FROM users WHERE is_deactivated = FALSE ORDER BY display_name LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Role        string             `json:"role"`
	Status      string             `json:"status"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
	IsBot       bool               `json:"is_bot"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Role,
			&i.Status,
			&i.LastSeen,
			&i.IsBot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutoHideDays = `-- name: UpdateAutoHideDays :exec
UPDATE users SET auto_hide_days = $2 WHERE id = $1
`

type UpdateAutoHideDaysParams struct {
	ID           pgtype.UUID `json:"id"`
	AutoHideDays int32       `json:"auto_hide_days"`
}

func (q *Queries) UpdateAutoHideDays(ctx context.Context, arg UpdateAutoHideDaysParams) error {
	_, err := q.db.Exec(ctx, updateAutoHideDays, arg.ID, arg.AutoHideDays)
	return err
}

const updateChannelSort = `-- name: UpdateChannelSort :exec
UPDATE users SET channel_sort = $2 WHERE id = $1
`

type UpdateChannelSortParams struct {
	ID          pgtype.UUID `json:"id"`
	ChannelSort string      `json:"channel_sort"`
}

func (q *Queries) UpdateChannelSort(ctx context.Context, arg UpdateChannelSortParams) error {
	_, err := q.db.Exec(ctx, updateChannelSort, arg.ID, arg.ChannelSort)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    display_name = coalesce($2, display_name),
    avatar_url = coalesce($3, avatar_url),
    status = coalesce($4, status),
    email = coalesce($5, email)
WHERE id = $1 RETURNING id, username, email, display_name, avatar_url, password_hash, role, status, last_seen, is_bot, bot_config, created_at, updated_at, is_deactivated, auto_hide_days, channel_sort
`

type UpdateUserParams struct {
	ID          pgtype.UUID `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Status      pgtype.Text `json:"status"`
	Email       pgtype.Text `json:"email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Status,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.LastSeen,
		&i.IsBot,
		&i.BotConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeactivated,
		&i.AutoHideDays,
		&i.ChannelSort,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET status = $2, last_seen = NOW() WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}
