// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannelWebhook = `-- name: CreateChannelWebhook :one
INSERT INTO channel_webhooks (channel_id, agent_id, name, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, agent_id, name, token, created_by, created_at
`

type CreateChannelWebhookParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	AgentID   pgtype.UUID `json:"agent_id"`
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateChannelWebhook(ctx context.Context, arg CreateChannelWebhookParams) (ChannelWebhook, error) {
	row := q.db.QueryRow(ctx, createChannelWebhook,
		arg.ChannelID,
		arg.AgentID,
		arg.Name,
		arg.CreatedBy,
	)
	var i ChannelWebhook
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AgentID,
		&i.Name,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannelWebhook = `-- name: DeleteChannelWebhook :exec
DELETE FROM channel_webhooks WHERE id = $1 AND channel_id = $2
`

type DeleteChannelWebhookParams struct {
	ID        pgtype.UUID `json:"id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

func (q *Queries) DeleteChannelWebhook(ctx context.Context, arg DeleteChannelWebhookParams) error {
	_, err := q.db.Exec(ctx, deleteChannelWebhook, arg.ID, arg.ChannelID)
	return err
}

const deleteChannelWebhookByID = `-- name: DeleteChannelWebhookByID :exec
DELETE FROM channel_webhooks WHERE id = $1
`

func (q *Queries) DeleteChannelWebhookByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannelWebhookByID, id)
	return err
}

const getWebhookByToken = `-- name: GetWebhookByToken :one
SELECT w.id, w.channel_id, w.agent_id, w.name, w.token, w.created_by, w.created_at, c.slug AS channel_slug, c.name AS channel_name,
       a.slug AS agent_slug, a.name AS agent_name, a.user_id AS agent_user_id
FROM channel_webhooks w
JOIN channels c ON c.id = w.channel_id
LEFT JOIN agents a ON a.id = w.agent_id
WHERE w.token = $1
`

type GetWebhookByTokenRow struct {
	ID          pgtype.UUID        `json:"id"`
	ChannelID   pgtype.UUID        `json:"channel_id"`
	AgentID     pgtype.UUID        `json:"agent_id"`
	Name        string             `json:"name"`
	Token       string             `json:"token"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ChannelSlug string             `json:"channel_slug"`
	ChannelName string             `json:"channel_name"`
	AgentSlug   pgtype.Text        `json:"agent_slug"`
	AgentName   pgtype.Text        `json:"agent_name"`
	AgentUserID pgtype.UUID        `json:"agent_user_id"`
}

func (q *Queries) GetWebhookByToken(ctx context.Context, token string) (GetWebhookByTokenRow, error) {
	row := q.db.QueryRow(ctx, getWebhookByToken, token)
	var i GetWebhookByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AgentID,
		&i.Name,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ChannelSlug,
		&i.ChannelName,
		&i.AgentSlug,
		&i.AgentName,
		&i.AgentUserID,
	)
	return i, err
}

const listChannelWebhooks = `-- name: ListChannelWebhooks :many
SELECT w.id, w.channel_id, w.agent_id, w.name, w.token, w.created_by, w.created_at, a.slug AS agent_slug, a.name AS agent_name
FROM channel_webhooks w
LEFT JOIN agents a ON a.id = w.agent_id
WHERE w.channel_id = $1
ORDER BY w.created_at DESC
`

type ListChannelWebhooksRow struct {
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	AgentID   pgtype.UUID        `json:"agent_id"`
	Name      string             `json:"name"`
	Token     string             `json:"token"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	AgentSlug pgtype.Text        `json:"agent_slug"`
	AgentName pgtype.Text        `json:"agent_name"`
}

func (q *Queries) ListChannelWebhooks(ctx context.Context, channelID pgtype.UUID) ([]ListChannelWebhooksRow, error) {
	rows, err := q.db.Query(ctx, listChannelWebhooks, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelWebhooksRow{}
	for rows.Next() {
		var i ListChannelWebhooksRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AgentID,
			&i.Name,
			&i.Token,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.AgentSlug,
			&i.AgentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
