export interface EmojiItem {
  emoji: string;
  name: string;
}

export interface EmojiCategory {
  name: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys & People',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: 'grinning face' },
      { emoji: '😃', name: 'grinning face with big eyes' },
      { emoji: '😄', name: 'grinning face with smiling eyes' },
      { emoji: '😁', name: 'beaming face' },
      { emoji: '😆', name: 'grinning squinting face' },
      { emoji: '😅', name: 'grinning face with sweat' },
      { emoji: '🤣', name: 'rolling on the floor laughing' },
      { emoji: '😂', name: 'face with tears of joy' },
      { emoji: '🙂', name: 'slightly smiling face' },
      { emoji: '🙃', name: 'upside down face' },
      { emoji: '😉', name: 'winking face' },
      { emoji: '😊', name: 'smiling face with smiling eyes' },
      { emoji: '😇', name: 'smiling face with halo' },
      { emoji: '🥰', name: 'smiling face with hearts' },
      { emoji: '😍', name: 'heart eyes' },
      { emoji: '🤩', name: 'star struck' },
      { emoji: '😘', name: 'face blowing a kiss' },
      { emoji: '😗', name: 'kissing face' },
      { emoji: '😚', name: 'kissing face with closed eyes' },
      { emoji: '😙', name: 'kissing face with smiling eyes' },
      { emoji: '🥲', name: 'smiling face with tear' },
      { emoji: '😋', name: 'face savoring food' },
      { emoji: '😛', name: 'face with tongue' },
      { emoji: '😜', name: 'winking face with tongue' },
      { emoji: '🤪', name: 'zany face' },
      { emoji: '😝', name: 'squinting face with tongue' },
      { emoji: '🤑', name: 'money mouth face' },
      { emoji: '🤗', name: 'hugging face' },
      { emoji: '🤭', name: 'face with hand over mouth' },
      { emoji: '🤫', name: 'shushing face' },
      { emoji: '🤔', name: 'thinking face' },
      { emoji: '🤐', name: 'zipper mouth face' },
      { emoji: '🤨', name: 'face with raised eyebrow' },
      { emoji: '😐', name: 'neutral face' },
      { emoji: '😑', name: 'expressionless face' },
      { emoji: '😶', name: 'face without mouth' },
      { emoji: '😏', name: 'smirking face' },
      { emoji: '😒', name: 'unamused face' },
      { emoji: '🙄', name: 'face with rolling eyes' },
      { emoji: '😬', name: 'grimacing face' },
      { emoji: '🤥', name: 'lying face' },
      { emoji: '😌', name: 'relieved face' },
      { emoji: '😔', name: 'pensive face' },
      { emoji: '😪', name: 'sleepy face' },
      { emoji: '🤤', name: 'drooling face' },
      { emoji: '😴', name: 'sleeping face' },
      { emoji: '😷', name: 'face with medical mask' },
      { emoji: '🤒', name: 'face with thermometer' },
      { emoji: '🤕', name: 'face with head bandage' },
      { emoji: '🤢', name: 'nauseated face' },
      { emoji: '🤮', name: 'face vomiting' },
      { emoji: '🥵', name: 'hot face' },
      { emoji: '🥶', name: 'cold face' },
      { emoji: '🥴', name: 'woozy face' },
      { emoji: '😵', name: 'face with crossed out eyes' },
      { emoji: '🤯', name: 'exploding head' },
      { emoji: '🤠', name: 'cowboy hat face' },
      { emoji: '🥳', name: 'partying face' },
      { emoji: '🥸', name: 'disguised face' },
      { emoji: '😎', name: 'smiling face with sunglasses' },
      { emoji: '🤓', name: 'nerd face' },
      { emoji: '🧐', name: 'face with monocle' },
      { emoji: '😕', name: 'confused face' },
      { emoji: '😟', name: 'worried face' },
      { emoji: '🙁', name: 'slightly frowning face' },
      { emoji: '😮', name: 'face with open mouth' },
      { emoji: '😯', name: 'hushed face' },
      { emoji: '😲', name: 'astonished face' },
      { emoji: '😳', name: 'flushed face' },
      { emoji: '🥺', name: 'pleading face' },
      { emoji: '😦', name: 'frowning face with open mouth' },
      { emoji: '😧', name: 'anguished face' },
      { emoji: '😨', name: 'fearful face' },
      { emoji: '😰', name: 'anxious face with sweat' },
      { emoji: '😥', name: 'sad but relieved face' },
      { emoji: '😢', name: 'crying face' },
      { emoji: '😭', name: 'loudly crying face' },
      { emoji: '😱', name: 'face screaming in fear' },
      { emoji: '😖', name: 'confounded face' },
      { emoji: '😣', name: 'persevering face' },
      { emoji: '😞', name: 'disappointed face' },
      { emoji: '😓', name: 'downcast face with sweat' },
      { emoji: '😩', name: 'weary face' },
      { emoji: '😫', name: 'tired face' },
      { emoji: '🥱', name: 'yawning face' },
      { emoji: '😤', name: 'face with steam from nose' },
      { emoji: '😡', name: 'pouting face' },
      { emoji: '😠', name: 'angry face' },
      { emoji: '🤬', name: 'face with symbols on mouth' },
      { emoji: '😈', name: 'smiling face with horns' },
      { emoji: '👿', name: 'angry face with horns' },
      { emoji: '💀', name: 'skull' },
      { emoji: '👻', name: 'ghost' },
      { emoji: '👽', name: 'alien' },
      { emoji: '🤖', name: 'robot' },
      { emoji: '💩', name: 'pile of poo' },
      { emoji: '🤡', name: 'clown face' },
    ],
  },
  {
    name: 'Hands & Gestures',
    icon: '👋',
    emojis: [
      { emoji: '👋', name: 'waving hand' },
      { emoji: '🤚', name: 'raised back of hand' },
      { emoji: '🖐️', name: 'hand with fingers splayed' },
      { emoji: '✋', name: 'raised hand' },
      { emoji: '🖖', name: 'vulcan salute' },
      { emoji: '👌', name: 'ok hand' },
      { emoji: '🤌', name: 'pinched fingers' },
      { emoji: '🤏', name: 'pinching hand' },
      { emoji: '✌️', name: 'victory hand' },
      { emoji: '🤞', name: 'crossed fingers' },
      { emoji: '🤟', name: 'love you gesture' },
      { emoji: '🤘', name: 'sign of the horns' },
      { emoji: '🤙', name: 'call me hand' },
      { emoji: '👈', name: 'backhand index pointing left' },
      { emoji: '👉', name: 'backhand index pointing right' },
      { emoji: '👆', name: 'backhand index pointing up' },
      { emoji: '👇', name: 'backhand index pointing down' },
      { emoji: '☝️', name: 'index pointing up' },
      { emoji: '👍', name: 'thumbs up' },
      { emoji: '👎', name: 'thumbs down' },
      { emoji: '✊', name: 'raised fist' },
      { emoji: '👊', name: 'oncoming fist' },
      { emoji: '🤛', name: 'left facing fist' },
      { emoji: '🤜', name: 'right facing fist' },
      { emoji: '👏', name: 'clapping hands' },
      { emoji: '🙌', name: 'raising hands' },
      { emoji: '👐', name: 'open hands' },
      { emoji: '🤲', name: 'palms up together' },
      { emoji: '🤝', name: 'handshake' },
      { emoji: '🙏', name: 'folded hands' },
      { emoji: '💪', name: 'flexed biceps' },
      { emoji: '🦾', name: 'mechanical arm' },
    ],
  },
  {
    name: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', name: 'dog face' },
      { emoji: '🐱', name: 'cat face' },
      { emoji: '🐭', name: 'mouse face' },
      { emoji: '🐹', name: 'hamster' },
      { emoji: '🐰', name: 'rabbit face' },
      { emoji: '🦊', name: 'fox' },
      { emoji: '🐻', name: 'bear' },
      { emoji: '🐼', name: 'panda' },
      { emoji: '🐨', name: 'koala' },
      { emoji: '🐯', name: 'tiger face' },
      { emoji: '🦁', name: 'lion' },
      { emoji: '🐮', name: 'cow face' },
      { emoji: '🐷', name: 'pig face' },
      { emoji: '🐸', name: 'frog' },
      { emoji: '🐵', name: 'monkey face' },
      { emoji: '🙈', name: 'see no evil monkey' },
      { emoji: '🙉', name: 'hear no evil monkey' },
      { emoji: '🙊', name: 'speak no evil monkey' },
      { emoji: '🐔', name: 'chicken' },
      { emoji: '🐧', name: 'penguin' },
      { emoji: '🐦', name: 'bird' },
      { emoji: '🦅', name: 'eagle' },
      { emoji: '🦆', name: 'duck' },
      { emoji: '🦉', name: 'owl' },
      { emoji: '🐺', name: 'wolf' },
      { emoji: '🐗', name: 'boar' },
      { emoji: '🐴', name: 'horse face' },
      { emoji: '🦄', name: 'unicorn' },
      { emoji: '🐝', name: 'honeybee' },
      { emoji: '🐛', name: 'bug' },
      { emoji: '🦋', name: 'butterfly' },
      { emoji: '🐌', name: 'snail' },
      { emoji: '🐙', name: 'octopus' },
      { emoji: '🦑', name: 'squid' },
      { emoji: '🦀', name: 'crab' },
      { emoji: '🐠', name: 'tropical fish' },
      { emoji: '🐟', name: 'fish' },
      { emoji: '🐬', name: 'dolphin' },
      { emoji: '🐳', name: 'spouting whale' },
      { emoji: '🐋', name: 'whale' },
      { emoji: '🦈', name: 'shark' },
      { emoji: '🐊', name: 'crocodile' },
      { emoji: '🐆', name: 'leopard' },
      { emoji: '🦓', name: 'zebra' },
      { emoji: '🦍', name: 'gorilla' },
      { emoji: '🐘', name: 'elephant' },
      { emoji: '🦏', name: 'rhinoceros' },
      { emoji: '🐪', name: 'camel' },
      { emoji: '🦒', name: 'giraffe' },
      { emoji: '🌸', name: 'cherry blossom' },
      { emoji: '🌹', name: 'rose' },
      { emoji: '🌻', name: 'sunflower' },
      { emoji: '🌺', name: 'hibiscus' },
      { emoji: '🌷', name: 'tulip' },
      { emoji: '🌱', name: 'seedling' },
      { emoji: '🌲', name: 'evergreen tree' },
      { emoji: '🌳', name: 'deciduous tree' },
      { emoji: '🌴', name: 'palm tree' },
      { emoji: '🍀', name: 'four leaf clover' },
      { emoji: '🍁', name: 'maple leaf' },
      { emoji: '🍂', name: 'fallen leaf' },
    ],
  },
  {
    name: 'Food & Drink',
    icon: '🍕',
    emojis: [
      { emoji: '🍎', name: 'red apple' },
      { emoji: '🍊', name: 'tangerine' },
      { emoji: '🍋', name: 'lemon' },
      { emoji: '🍌', name: 'banana' },
      { emoji: '🍉', name: 'watermelon' },
      { emoji: '🍇', name: 'grapes' },
      { emoji: '🍓', name: 'strawberry' },
      { emoji: '🫐', name: 'blueberries' },
      { emoji: '🍑', name: 'peach' },
      { emoji: '🥭', name: 'mango' },
      { emoji: '🍍', name: 'pineapple' },
      { emoji: '🥥', name: 'coconut' },
      { emoji: '🥝', name: 'kiwi fruit' },
      { emoji: '🍅', name: 'tomato' },
      { emoji: '🥑', name: 'avocado' },
      { emoji: '🌽', name: 'ear of corn' },
      { emoji: '🌶️', name: 'hot pepper' },
      { emoji: '🥒', name: 'cucumber' },
      { emoji: '🥬', name: 'leafy green' },
      { emoji: '🥦', name: 'broccoli' },
      { emoji: '🧄', name: 'garlic' },
      { emoji: '🍞', name: 'bread' },
      { emoji: '🥐', name: 'croissant' },
      { emoji: '🍕', name: 'pizza' },
      { emoji: '🍔', name: 'hamburger' },
      { emoji: '🍟', name: 'french fries' },
      { emoji: '🌭', name: 'hot dog' },
      { emoji: '🥪', name: 'sandwich' },
      { emoji: '🌮', name: 'taco' },
      { emoji: '🌯', name: 'burrito' },
      { emoji: '🍣', name: 'sushi' },
      { emoji: '🍜', name: 'steaming bowl' },
      { emoji: '🍝', name: 'spaghetti' },
      { emoji: '🍲', name: 'pot of food' },
      { emoji: '🍛', name: 'curry rice' },
      { emoji: '🍩', name: 'doughnut' },
      { emoji: '🍪', name: 'cookie' },
      { emoji: '🎂', name: 'birthday cake' },
      { emoji: '🍰', name: 'shortcake' },
      { emoji: '🧁', name: 'cupcake' },
      { emoji: '🍫', name: 'chocolate bar' },
      { emoji: '🍬', name: 'candy' },
      { emoji: '🍭', name: 'lollipop' },
      { emoji: '🍿', name: 'popcorn' },
      { emoji: '☕', name: 'hot beverage coffee' },
      { emoji: '🍵', name: 'teacup' },
      { emoji: '🥤', name: 'cup with straw' },
      { emoji: '🍺', name: 'beer mug' },
      { emoji: '🍻', name: 'clinking beer mugs' },
      { emoji: '🥂', name: 'clinking glasses' },
      { emoji: '🍷', name: 'wine glass' },
      { emoji: '🍸', name: 'cocktail glass' },
      { emoji: '🧃', name: 'beverage box' },
    ],
  },
  {
    name: 'Activities',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', name: 'soccer ball' },
      { emoji: '🏀', name: 'basketball' },
      { emoji: '🏈', name: 'american football' },
      { emoji: '⚾', name: 'baseball' },
      { emoji: '🥎', name: 'softball' },
      { emoji: '🎾', name: 'tennis' },
      { emoji: '🏐', name: 'volleyball' },
      { emoji: '🏉', name: 'rugby football' },
      { emoji: '🥏', name: 'flying disc' },
      { emoji: '🎱', name: 'billiards' },
      { emoji: '🏓', name: 'ping pong' },
      { emoji: '🏸', name: 'badminton' },
      { emoji: '🥊', name: 'boxing glove' },
      { emoji: '🎯', name: 'direct hit' },
      { emoji: '⛳', name: 'flag in hole golf' },
      { emoji: '🎮', name: 'video game' },
      { emoji: '🕹️', name: 'joystick' },
      { emoji: '🎲', name: 'game die' },
      { emoji: '🧩', name: 'puzzle piece' },
      { emoji: '♟️', name: 'chess pawn' },
      { emoji: '🎭', name: 'performing arts' },
      { emoji: '🎨', name: 'artist palette' },
      { emoji: '🎬', name: 'clapper board' },
      { emoji: '🎤', name: 'microphone' },
      { emoji: '🎧', name: 'headphone' },
      { emoji: '🎵', name: 'musical note' },
      { emoji: '🎶', name: 'musical notes' },
      { emoji: '🎹', name: 'musical keyboard piano' },
      { emoji: '🎸', name: 'guitar' },
      { emoji: '🥁', name: 'drum' },
      { emoji: '🎺', name: 'trumpet' },
      { emoji: '🏆', name: 'trophy' },
      { emoji: '🥇', name: 'gold medal' },
      { emoji: '🥈', name: 'silver medal' },
      { emoji: '🥉', name: 'bronze medal' },
      { emoji: '🎪', name: 'circus tent' },
    ],
  },
  {
    name: 'Travel & Places',
    icon: '✈️',
    emojis: [
      { emoji: '🚗', name: 'automobile car' },
      { emoji: '🚕', name: 'taxi' },
      { emoji: '🚌', name: 'bus' },
      { emoji: '🚎', name: 'trolleybus' },
      { emoji: '🏎️', name: 'racing car' },
      { emoji: '🚓', name: 'police car' },
      { emoji: '🚑', name: 'ambulance' },
      { emoji: '🚒', name: 'fire engine' },
      { emoji: '✈️', name: 'airplane' },
      { emoji: '🚀', name: 'rocket' },
      { emoji: '🛸', name: 'flying saucer ufo' },
      { emoji: '🚁', name: 'helicopter' },
      { emoji: '⛵', name: 'sailboat' },
      { emoji: '🚢', name: 'ship' },
      { emoji: '🚂', name: 'locomotive train' },
      { emoji: '🚲', name: 'bicycle' },
      { emoji: '🏠', name: 'house' },
      { emoji: '🏢', name: 'office building' },
      { emoji: '🏥', name: 'hospital' },
      { emoji: '🏫', name: 'school' },
      { emoji: '🏰', name: 'castle' },
      { emoji: '⛪', name: 'church' },
      { emoji: '🕌', name: 'mosque' },
      { emoji: '🗼', name: 'tokyo tower' },
      { emoji: '🗽', name: 'statue of liberty' },
      { emoji: '⛰️', name: 'mountain' },
      { emoji: '🌋', name: 'volcano' },
      { emoji: '🏖️', name: 'beach with umbrella' },
      { emoji: '🏕️', name: 'camping' },
      { emoji: '🌅', name: 'sunrise' },
      { emoji: '🌄', name: 'sunrise over mountains' },
      { emoji: '🌇', name: 'sunset' },
      { emoji: '🌆', name: 'cityscape at dusk' },
      { emoji: '🌃', name: 'night with stars' },
      { emoji: '🌉', name: 'bridge at night' },
      { emoji: '🌌', name: 'milky way' },
      { emoji: '🎡', name: 'ferris wheel' },
      { emoji: '🎢', name: 'roller coaster' },
    ],
  },
  {
    name: 'Objects',
    icon: '💡',
    emojis: [
      { emoji: '⌚', name: 'watch' },
      { emoji: '📱', name: 'mobile phone' },
      { emoji: '💻', name: 'laptop computer' },
      { emoji: '⌨️', name: 'keyboard' },
      { emoji: '🖥️', name: 'desktop computer' },
      { emoji: '🖨️', name: 'printer' },
      { emoji: '🖱️', name: 'computer mouse' },
      { emoji: '💾', name: 'floppy disk' },
      { emoji: '💿', name: 'optical disk cd' },
      { emoji: '📷', name: 'camera' },
      { emoji: '📹', name: 'video camera' },
      { emoji: '🔦', name: 'flashlight' },
      { emoji: '💡', name: 'light bulb' },
      { emoji: '🔋', name: 'battery' },
      { emoji: '🔌', name: 'electric plug' },
      { emoji: '💰', name: 'money bag' },
      { emoji: '💳', name: 'credit card' },
      { emoji: '💎', name: 'gem stone diamond' },
      { emoji: '🔧', name: 'wrench' },
      { emoji: '🔨', name: 'hammer' },
      { emoji: '🛠️', name: 'hammer and wrench tools' },
      { emoji: '⚙️', name: 'gear' },
      { emoji: '🔩', name: 'nut and bolt' },
      { emoji: '🔑', name: 'key' },
      { emoji: '🗝️', name: 'old key' },
      { emoji: '🔒', name: 'locked' },
      { emoji: '🔓', name: 'unlocked' },
      { emoji: '📦', name: 'package' },
      { emoji: '📫', name: 'mailbox' },
      { emoji: '📝', name: 'memo' },
      { emoji: '📁', name: 'file folder' },
      { emoji: '📂', name: 'open file folder' },
      { emoji: '📄', name: 'page facing up document' },
      { emoji: '📊', name: 'bar chart' },
      { emoji: '📈', name: 'chart increasing' },
      { emoji: '📉', name: 'chart decreasing' },
      { emoji: '📌', name: 'pushpin' },
      { emoji: '📎', name: 'paperclip' },
      { emoji: '✂️', name: 'scissors' },
      { emoji: '📐', name: 'triangular ruler' },
      { emoji: '🗑️', name: 'wastebasket trash' },
    ],
  },
  {
    name: 'Symbols & Flags',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', name: 'red heart' },
      { emoji: '🧡', name: 'orange heart' },
      { emoji: '💛', name: 'yellow heart' },
      { emoji: '💚', name: 'green heart' },
      { emoji: '💙', name: 'blue heart' },
      { emoji: '💜', name: 'purple heart' },
      { emoji: '🖤', name: 'black heart' },
      { emoji: '🤍', name: 'white heart' },
      { emoji: '🤎', name: 'brown heart' },
      { emoji: '💔', name: 'broken heart' },
      { emoji: '❣️', name: 'heart exclamation' },
      { emoji: '💕', name: 'two hearts' },
      { emoji: '💞', name: 'revolving hearts' },
      { emoji: '💓', name: 'beating heart' },
      { emoji: '💗', name: 'growing heart' },
      { emoji: '💖', name: 'sparkling heart' },
      { emoji: '💘', name: 'heart with arrow' },
      { emoji: '💝', name: 'heart with ribbon' },
      { emoji: '💟', name: 'heart decoration' },
      { emoji: '☮️', name: 'peace symbol' },
      { emoji: '✝️', name: 'latin cross' },
      { emoji: '☪️', name: 'star and crescent' },
      { emoji: '⭐', name: 'star' },
      { emoji: '🌟', name: 'glowing star' },
      { emoji: '💫', name: 'dizzy star' },
      { emoji: '✨', name: 'sparkles' },
      { emoji: '⚡', name: 'high voltage lightning' },
      { emoji: '🔥', name: 'fire' },
      { emoji: '💥', name: 'collision boom' },
      { emoji: '🎉', name: 'party popper' },
      { emoji: '🎊', name: 'confetti ball' },
      { emoji: '✅', name: 'check mark' },
      { emoji: '❌', name: 'cross mark' },
      { emoji: '❓', name: 'question mark' },
      { emoji: '❗', name: 'exclamation mark' },
      { emoji: '💯', name: 'hundred points' },
      { emoji: '🔴', name: 'red circle' },
      { emoji: '🟢', name: 'green circle' },
      { emoji: '🔵', name: 'blue circle' },
      { emoji: '🟡', name: 'yellow circle' },
      { emoji: '⚫', name: 'black circle' },
      { emoji: '⚪', name: 'white circle' },
      { emoji: '🏳️', name: 'white flag' },
      { emoji: '🏴', name: 'black flag' },
      { emoji: '🚩', name: 'triangular flag red flag' },
      { emoji: '🏁', name: 'chequered flag' },
      { emoji: '👀', name: 'eyes' },
      { emoji: '💬', name: 'speech balloon' },
      { emoji: '💭', name: 'thought balloon' },
      { emoji: '🗨️', name: 'left speech bubble' },
      { emoji: '♻️', name: 'recycling symbol' },
      { emoji: '⚠️', name: 'warning' },
      { emoji: '🚫', name: 'prohibited' },
      { emoji: '🔔', name: 'bell' },
      { emoji: '🔕', name: 'bell with slash muted' },
    ],
  },
];
